/**
 * 일주(日柱) 120유형 데이터
 *
 * 60 일주 × 2 성별 = 120유형
 * 랜딩 카드, 결과 페이지, 공유 이미지, 리포트, 궁합에 공통으로 사용
 */

export interface IljuType {
  /** 고유 ID: "갑자-m", "갑자-f" */
  id: string;

  /** 일주 한글: "갑자" */
  ilju: string;

  /** 일주 한자: "甲子" */
  hanja: string;

  /** 성별 */
  gender: 'male' | 'female';

  /** 유형 별명 (캐릭터 카드 타이틀) */
  name: string;

  /** 이모지 (카드 대표 아이콘) */
  emoji: string;

  /** 한줄 태그라인 (카드 서브타이틀) */
  tagline: string;

  /** 천간 오행 */
  stemElement: '목(木)' | '화(火)' | '토(土)' | '금(金)' | '수(水)';

  /** 지지 오행 */
  branchElement: '목(木)' | '화(火)' | '토(土)' | '금(金)' | '수(水)';

  /** 음양 */
  yinyang: '양(陽)' | '음(陰)';

  /** UI 태그 색상 (Tailwind 클래스) */
  tagColor: string;

  /** 강점 (3~4개) */
  strengths: string[];

  /** 약점 (2~3개) */
  weaknesses: string[];

  /** 한마디 (말풍선 — 캐릭터의 대사) */
  quote: string;

  /** 성격 요약 (2~3줄, 친구 말투) */
  description: string;

  /** 잘 맞는 일주 ID */
  bestMatch: string;

  /** 조심할 일주 ID */
  worstMatch: string;

  /** 캐치포인트 — 이 이름이 붙은 사주적 근거 한 줄 */
  catchpoint: string;

  /** 희귀도 (1~5, 5가 가장 희귀) */
  rarity: number;

  /** 대표 이미지 URL (직접 업로드) */
  imageUrl?: string;
}

// ═══════════════════════════════════════
// 네이밍 규칙
// ═══════════════════════════════════════
//
// 핵심: 이름만 들으면 "아 그런 사람 있다ㅋㅋ" 하고 바로 떠올라야 함
//
// 로직: 사주 오행 조합에서 "가장 재밌는 행동/특성 하나"를 추출
//   1) 천간+지지 오행 조합이 만드는 에너지 특성 파악
//   2) 그 에너지가 실생활에서 드러나는 구체적 행동 포착
//   3) 그 행동을 가장 재밌게 표현하는 한마디로 이름 짓기
//
// 검증된 이름 패턴 (다양하게 섞어 쓸 것):
//   "행동 묘사"         — 일단 출발하는 사람, 급할 게 없는 사람
//   "특성+역할"         — 걱정 삭제 담당, 조용한 승부사
//   "별명/밈형"         — 츤데레 본체, 주인공 체질
//   "인용/대사형"        — '아무거나' 불가
//   "과장 수식"         — 감성 수신율 200%, 눈치 만렙
//   "인간+X" (아껴 쓸 것) — 인간 불도저 (진짜 딱 맞을 때만)
//
// ✗ 금지:
//   - 자연물 직접 비유 ("든든한 산") → 사람 아닌 느낌
//   - 추상 형용사 나열 ("반전 매력 폭발") → 밋밋
//   - 같은 패턴 연속 반복 → 식상
//   - "인간 탱크" 같은 뻔한 비유 → 재미 없음

export const ILJU_TYPES: IljuType[] = [
  // ── 1. 갑자 (甲子) 남성 — 목(양) + 수 ──
  {
    id: "갑자-m",
    ilju: "갑자",
    hanja: "甲子",
    gender: "male",
    name: "인간 불도저",
    emoji: "🚜",
    tagline: "고민 끝나기 전에 이미 가고 있음",
    stemElement: "목(木)",
    branchElement: "수(水)",
    yinyang: "양(陽)",
    tagColor: "bg-neon-green",
    strengths: ["추진력", "독립심", "창의적 문제해결"],
    weaknesses: ["속도가 빠른 편", "혼자 다 하려 함"],
    quote: "고민은 가면서 해.",
    description: "큰 나무가 깊은 물 위에 뿌리를 내린 형상이야. 남들이 '어떡하지' 할 때 이미 출발해 있는 타입이거든. 혼자서도 잘하는데, 가끔은 옆 사람 손 좀 잡아주면 더 멀리 갈 수 있어.",
    catchpoint: "목양(甲) + 수(子) = 큰 나무에 물 공급 → 멈출 줄 모르는 성장 에너지",
    bestMatch: "기사-f",
    worstMatch: "경오-f",
    rarity: 3,
  },

  // ── 2. 을묘 (乙卯) 여성 — 목(음) + 목 ──
  {
    id: "을묘-f",
    ilju: "을묘",
    hanja: "乙卯",
    gender: "female",
    name: "감성 예술가",
    emoji: "🌸",
    tagline: "남들이 못 느끼는 걸 혼자 잡아냄",
    stemElement: "목(木)",
    branchElement: "목(木)",
    yinyang: "음(陰)",
    tagColor: "bg-lavender",
    strengths: ["창의력", "공감력", "직관"],
    weaknesses: ["신중한 선택", "감수성이 풍부함"],
    quote: "그 사람 표정 봤어? 뭔가 있어.",
    description: "꽃이 꽃밭에 핀 것 같은 사주야. 감수성이 정말 풍부해서 남들이 못 느끼는 걸 캐치하거든. 분위기 한 번에 파악하고, 누가 기분 나쁜지 말 안 해도 알아. 근데 너무 많이 느끼다 보면 본인이 지칠 수 있어.",
    catchpoint: "목음(乙) + 목(卯) = 꽃이 꽃밭에 핌 → 감수성이 두 배로 증폭",
    bestMatch: "경진-m",
    worstMatch: "신유-m",
    rarity: 2,
  },

  // ── 3. 병오 (丙午) 남성 — 화(양) + 화 ──
  {
    id: "병오-m",
    ilju: "병오",
    hanja: "丙午",
    gender: "male",
    name: "존재감 풀옵션",
    emoji: "☀️",
    tagline: "등장하는 순간 시끄러워짐",
    stemElement: "화(火)",
    branchElement: "화(火)",
    yinyang: "양(陽)",
    tagColor: "bg-pop-orange",
    strengths: ["카리스마", "행동력", "긍정 에너지"],
    weaknesses: ["참을성 부족", "가끔 과한 자신감"],
    quote: "일단 하고 보는 거지, 뭘 고민해.",
    description: "화(火)가 두 겹이라 에너지가 진짜 장난 아니야. 어디 가든 주인공 포지션에 서게 되거든. 근데 가끔 너무 뜨거워서 옆 사람이 '나는..?' 할 수 있다는 것만 기억해.",
    catchpoint: "화양(丙) + 화(午) = 불이 두 겹 → 에너지 과잉, 존재감 폭발",
    bestMatch: "임자-f",
    worstMatch: "임자-m",
    rarity: 4,
  },

  // ── 4. 경진 (庚辰) 남성 — 금(양) + 토 ──
  {
    id: "경진-m",
    ilju: "경진",
    hanja: "庚辰",
    gender: "male",
    name: "직진 본능",
    emoji: "🦁",
    tagline: "후진 기어 없음. 직진만 있음.",
    stemElement: "금(金)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-charcoal",
    strengths: ["결단력", "리더십", "책임감"],
    weaknesses: ["고집", "융통성 부족"],
    quote: "벽이 있으면 부숨.",
    description: "단단한 쇠가 산 위에 올라앉은 형상이야. 한번 물면 진짜 안 놓거든. '이 사람 왜 아직도 저걸 하고 있지?' 했는데 결국 해내는 게 이 유형이야. 대신 방향이 틀렸을 때도 계속 가는 게 함정이라, 가끔 멈추고 돌아보는 것도 방법이야.",
    catchpoint: "금양(庚) + 토(辰) = 쇠가 산 위에 → 단단함+높은 위치, 후진 기어 없음",
    bestMatch: "을묘-f",
    worstMatch: "갑인-f",
    rarity: 3,
  },

  // ── 5. 임오 (壬午) 여성 — 수(양) + 화 ──
  {
    id: "임오-f",
    ilju: "임오",
    hanja: "壬午",
    gender: "female",
    name: "츤데레 본체",
    emoji: "🎭",
    tagline: "쿨한 줄 알았지? 속은 완전 반대",
    stemElement: "수(水)",
    branchElement: "화(火)",
    yinyang: "양(陽)",
    tagColor: "bg-pink",
    strengths: ["적응력", "다재다능", "반전 매력"],
    weaknesses: ["내면 갈등", "속마음 숨김"],
    quote: "관심 없는 척 하는 거 다 티나? ...진짜?",
    description: "물 위에 불이 있는 사주야. 겉은 쿨하고 덤덤한데 속에서는 난리가 나고 있거든. 이 갭 때문에 사람들이 더 끌리는 타입이야. 근데 가끔 본인도 '진짜 나는 어느 쪽이지?' 헷갈릴 수 있어.",
    catchpoint: "수양(壬) + 화(午) = 물 위에 불 → 겉과 속의 온도차, 반전 갭",
    bestMatch: "병오-m",
    worstMatch: "무진-m",
    rarity: 4,
  },

  // ── 6. 정해 (丁亥) 여성 — 화(음) + 수 ──
  {
    id: "정해-f",
    ilju: "정해",
    hanja: "丁亥",
    gender: "female",
    name: "태어나길 눈치 만렙",
    emoji: "🕯️",
    tagline: "말 안 해도 다 알고 있음",
    stemElement: "화(火)",
    branchElement: "수(水)",
    yinyang: "음(陰)",
    tagColor: "bg-pop-orange",
    strengths: ["인내력", "통찰력", "감정 지능"],
    weaknesses: ["남을 먼저 챙기는 편", "표현 서투름"],
    quote: "아까 그 말, 기분 나빴지? 알아.",
    description: "큰 바다 위에 촛불이 켜진 형상이야. 조용한데 상황 파악이 미쳤거든. 누가 뭘 느끼는지 말 안 해도 다 읽어. 근데 남의 감정만 챙기다 정작 본인은 못 챙기는 경우가 있어. 가끔은 본인 먼저야.",
    catchpoint: "화음(丁) + 수(亥) = 바다 위 촛불 → 작지만 절대 안 꺼지는 통찰력",
    bestMatch: "임자-m",
    worstMatch: "계사-m",
    rarity: 3,
  },

  // ── 7. 무진 (戊辰) 여성 — 토(양) + 토 ──
  {
    id: "무진-f",
    ilju: "무진",
    hanja: "戊辰",
    gender: "female",
    name: "걱정 삭제 담당",
    emoji: "🧸",
    tagline: "옆에만 있어도 왠지 다 괜찮아짐",
    stemElement: "토(土)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-mustard",
    strengths: ["안정감", "포용력", "끈기"],
    weaknesses: ["익숙한 방식 선호", "속마음 감춤"],
    quote: "괜찮아, 내가 있잖아.",
    description: "토(土)가 두 겹이라 안정감이 장난 아니야. 이 사람 옆에 있으면 왜인지 마음이 편해지거든. 주변 사람들이 힘들 때 제일 먼저 찾는 타입인데, 본인 감정은 잘 안 꺼내서 가끔 혼자 무거운 걸 다 지고 있을 때가 있어.",
    catchpoint: "토양(戊) + 토(辰) = 흙 두 겹 → 흔들림 없는 안정감, 주변을 안심시킴",
    bestMatch: "갑자-m",
    worstMatch: "갑인-m",
    rarity: 2,
  },

  // ── 8. 신유 (辛酉) 남성 — 금(음) + 금 ──
  {
    id: "신유-m",
    ilju: "신유",
    hanja: "辛酉",
    gender: "male",
    name: "'아무거나' 불가",
    emoji: "💎",
    tagline: "기준이 확실하고 절대 안 낮춤",
    stemElement: "금(金)",
    branchElement: "금(金)",
    yinyang: "음(陰)",
    tagColor: "bg-lavender",
    strengths: ["분석력", "완벽주의", "심미안"],
    weaknesses: ["기준이 높은 편", "혼자가 편함"],
    quote: "아무거나는 못 해. 그게 나야.",
    description: "금(金)이 두 겹이라 기준이 진짜 높아. '아무거나 먹자' 했다가 30분째 메뉴판 보고 있는 타입이거든. 대신 고른 건 진짜 좋아. 본인한테도 남한테도 기준이 높은데, 완벽하지 않아도 괜찮다는 거 가끔 떠올려봐.",
    catchpoint: "금음(辛) + 금(酉) = 보석이 보석 위에 → 기준이 두 배, '아무거나'가 불가능",
    bestMatch: "병오-f",
    worstMatch: "을묘-f",
    rarity: 4,
  },

  // ── 9. 계사 (癸巳) 여성 — 수(음) + 화 ──
  {
    id: "계사-f",
    ilju: "계사",
    hanja: "癸巳",
    gender: "female",
    name: "조용한 승부사",
    emoji: "🐍",
    tagline: "이미 세 수 앞을 보고 있음",
    stemElement: "수(水)",
    branchElement: "화(火)",
    yinyang: "음(陰)",
    tagColor: "bg-charcoal",
    strengths: ["전략적 사고", "관찰력", "집중력"],
    weaknesses: ["확인이 필요한 타입", "속내 안 보여줌"],
    quote: "다 계획이 있었어.",
    description: "작은 물이 불꽃 위를 흐르는 사주야. 겉으로는 조용한데 머릿속에서는 항상 시뮬레이션이 돌아가고 있거든. '걔 조용하더니 갑자기 일 터뜨림' — 이게 이 유형이야. 근데 너무 혼자 계산하다 보면 주변이 멀어질 수 있어.",
    catchpoint: "수음(癸) + 화(巳) = 물이 불 위를 흐름 → 조용한데 머릿속은 풀가동",
    bestMatch: "무진-m",
    worstMatch: "정해-m",
    rarity: 5,
  },

  // ── 10. 기미 (己未) 남성 — 토(음) + 토 ──
  {
    id: "기미-m",
    ilju: "기미",
    hanja: "己未",
    gender: "male",
    name: "마이페이스 힐러",
    emoji: "🐢",
    tagline: "같이 놀고 있었는데 어느샌가 다함",
    stemElement: "토(土)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-mustard",
    strengths: ["성실함", "배려", "지구력"],
    weaknesses: ["신중한 선택", "변화에 느림"],
    quote: "급하게 안 가도 돼. 어차피 도착해.",
    description: "주변에서 '빨리 해!' 하면 오히려 더 느려지는 타입이야. 근데 이 사람이 무서운 게, 느리지만 결국 다 해내거든. 사람 챙기는 것도 잘하고 성실한데, 결정을 너무 오래 고민할 때가 있어. 가끔은 80%에서 고 하는 것도 방법이야.",
    catchpoint: "토음(己) + 토(未) = 따뜻한 흙 두 겹 → 느린데 결국 다 키워냄",
    bestMatch: "갑자-f",
    worstMatch: "계사-f",
    rarity: 2,
  },

  // ── 11. 갑인 (甲寅) 여성 — 목(양) + 목 ──
  {
    id: "갑인-f",
    ilju: "갑인",
    hanja: "甲寅",
    gender: "female",
    name: "못 참는 정의파",
    emoji: "⚡",
    tagline: "불의 보면 그냥 못 참음",
    stemElement: "목(木)",
    branchElement: "목(木)",
    yinyang: "양(陽)",
    tagColor: "bg-neon-green",
    strengths: ["정의감", "용기", "솔직함"],
    weaknesses: ["의견 표현이 적극적", "참는 게 어려움"],
    quote: "그건 아닌데? 그건 진짜 아닌데?",
    description: "큰 나무가 호랑이 위에 앉은 사주야. 불의 보면 참는 버튼이 고장나거든. 덕분에 주변에서 '저 사람은 진짜다' 소리를 들어. 근데 가끔 싸울 필요 없는 데서도 싸우고 있을 때가 있어.",
    catchpoint: "목양(甲) + 목(寅) = 나무가 호랑이 위에 → 정의감이 폭발, 참는 게 불가",
    bestMatch: "기미-m",
    worstMatch: "경진-m",
    rarity: 3,
  },

  // ── 12. 을해 (乙亥) 남성 — 목(음) + 수 ──
  {
    id: "을해-m",
    ilju: "을해",
    hanja: "乙亥",
    gender: "male",
    name: "적응력 풀옵션",
    emoji: "🌿",
    tagline: "어디 가든 자연스럽게 스며들어 있음",
    stemElement: "목(木)",
    branchElement: "수(水)",
    yinyang: "음(陰)",
    tagColor: "bg-neon-green",
    strengths: ["적응력", "사교성", "유연함"],
    weaknesses: ["유연한 편", "눈치 과잉"],
    quote: "다 좋아~ 나는 다 괜찮아~",
    description: "작은 풀이 물 위에서 흘러가는 사주야. 어떤 모임에 가든 자연스럽게 녹아들거든. 근데 너무 맞추다 보면 '진짜 내 의견은 뭐였지?' 할 때가 있어. 가끔은 '나는 이게 싫어'도 말해봐.",
    catchpoint: "목음(乙) + 수(亥) = 풀이 물 위에 → 어디서든 스며드는 적응력",
    bestMatch: "병오-f",
    worstMatch: "신유-f",
    rarity: 2,
  },

  // ── 13. 병자 (丙子) 여성 — 화(양) + 수 ──
  {
    id: "병자-f",
    ilju: "병자",
    hanja: "丙子",
    gender: "female",
    name: "열정 과부하",
    emoji: "🔥",
    tagline: "몸이 두 개여도 모자람",
    stemElement: "화(火)",
    branchElement: "수(水)",
    yinyang: "양(陽)",
    tagColor: "bg-pop-orange",
    strengths: ["열정", "멀티태스킹", "추진력"],
    weaknesses: ["번아웃 위험", "다 하고 싶음"],
    quote: "이것도 하고 싶고 저것도 하고 싶고... 다 할 거야.",
    description: "불이 물 위에서 타는 사주야. 에너지가 넘치는데 그걸 제어하는 물도 같이 있거든. 관심사가 너무 많아서 몸이 하나로는 부족한 타입이야. 다 하고 싶은 마음은 알겠는데, 가끔은 하나에 집중하는 것도 전략이야.",
    catchpoint: "화양(丙) + 수(子) = 불이 물 위에서 탐 → 에너지 과다, 하고 싶은 게 폭발",
    bestMatch: "경진-m",
    worstMatch: "임오-m",
    rarity: 3,
  },

  // ── 14. 정묘 (丁卯) 남성 — 화(음) + 목 ──
  {
    id: "정묘-m",
    ilju: "정묘",
    hanja: "丁卯",
    gender: "male",
    name: "타고난 볼매",
    emoji: "🕯️",
    tagline: "첫인상은 조용한데 알면 알수록 빠져듦",
    stemElement: "화(火)",
    branchElement: "목(木)",
    yinyang: "음(陰)",
    tagColor: "bg-pop-orange",
    strengths: ["매력", "섬세함", "창의력"],
    weaknesses: ["조심스러운 편", "걱정 많음"],
    quote: "나? 별로 특별한 건 없는데... (주변: 아니거든)",
    description: "작은 불꽃이 나무를 만나서 따뜻하게 타는 사주야. 처음엔 별 존재감이 없어 보이는데 알면 알수록 빠져드는 타입이거든. 본인은 모르는데 주변에서 '너 매력 있어'라는 말 진짜 많이 들을 거야.",
    catchpoint: "화음(丁) + 목(卯) = 촛불이 나무를 만남 → 따뜻하게 타오르는 은근한 매력",
    bestMatch: "임자-f",
    worstMatch: "계사-f",
    rarity: 3,
  },

  // ── 15. 무오 (戊午) 여성 — 토(양) + 화 ──
  {
    id: "무오-f",
    ilju: "무오",
    hanja: "戊午",
    gender: "female",
    name: "엄마 같은 보스",
    emoji: "👑",
    tagline: "어느샌가 다 따라가고 있음",
    stemElement: "토(土)",
    branchElement: "화(火)",
    yinyang: "양(陽)",
    tagColor: "bg-mustard",
    strengths: ["리더십", "배려", "실행력"],
    weaknesses: ["참견 과다", "본인은 안 쉼"],
    quote: "밥은 먹었어? 그건 내가 할게.",
    description: "흙이 불 위에 앉은 사주야. 따뜻한데 단단하거든. 조직에서 '이 사람이 있으면 돌아간다'는 소리 듣는 타입이야. 근데 남 챙기느라 정작 본인이 쉴 시간을 안 만들어서 그게 좀 걱정이야.",
    catchpoint: "토양(戊) + 화(午) = 흙이 불 위에 → 따뜻하면서 단단한 리더십",
    bestMatch: "갑자-m",
    worstMatch: "갑인-m",
    rarity: 2,
  },

  // ── 16. 기사 (己巳) 남성 — 토(음) + 화 ──
  {
    id: "기사-m",
    ilju: "기사",
    hanja: "己巳",
    gender: "male",
    name: "순둥이 전략가",
    emoji: "🐍",
    tagline: "순해 보여서 방심했다간 큰일 남",
    stemElement: "토(土)",
    branchElement: "화(火)",
    yinyang: "음(陰)",
    tagColor: "bg-mustard",
    strengths: ["야심", "인내", "계획력"],
    weaknesses: ["속내 안 보여줌", "느린 실행"],
    quote: "지금은 때가 아니야. 근데 때 되면 움직여.",
    description: "부드러운 흙 속에 뜨거운 불이 숨어 있는 사주야. 겉으로는 순한데 속에는 야망이 있거든. '저 사람 욕심 없어 보이는데?' 했는데 알고 보면 다 계획이 있었던 타입이야.",
    catchpoint: "토음(己) + 화(巳) = 부드러운 흙 속에 불 → 순해 보이지만 속에 야망",
    bestMatch: "갑자-f",
    worstMatch: "을묘-m",
    rarity: 4,
  },

  // ── 17. 경오 (庚午) 여성 — 금(양) + 화 ──
  {
    id: "경오-f",
    ilju: "경오",
    hanja: "庚午",
    gender: "female",
    name: "돌려 말하기 0%",
    emoji: "⚔️",
    tagline: "할 말 다 하고 할 것도 다 함",
    stemElement: "금(金)",
    branchElement: "화(火)",
    yinyang: "양(陽)",
    tagColor: "bg-charcoal",
    strengths: ["결단력", "실행력", "솔직함"],
    weaknesses: ["표현이 너무 직접적", "의견 표현이 적극적"],
    quote: "돌려 말하면 더 복잡해지잖아.",
    description: "쇠가 불 속에서 달궈지는 사주야. 그래서 뜨겁고 날카로워. 회의 시간에 아무도 말 못 할 때 '그거 아닌 것 같은데요' 하는 사람이 이 유형이거든. 덕분에 신뢰받는데, 가끔 부드럽게 말해도 내용은 전달돼.",
    catchpoint: "금양(庚) + 화(午) = 쇠가 불에 달궈짐 → 뜨겁고 날카로운 직설",
    bestMatch: "을해-m",
    worstMatch: "갑자-m",
    rarity: 4,
  },

  // ── 18. 신해 (辛亥) 남성 — 금(음) + 수 ──
  {
    id: "신해-m",
    ilju: "신해",
    hanja: "辛亥",
    gender: "male",
    name: "충전은 혼자서",
    emoji: "🎧",
    tagline: "사람은 좋은데 충전은 혼자",
    stemElement: "금(金)",
    branchElement: "수(水)",
    yinyang: "음(陰)",
    tagColor: "bg-lavender",
    strengths: ["독립심", "지적 호기심", "냉철함"],
    weaknesses: ["혼자 충전이 필요함", "감정 표현 서투름"],
    quote: "주말? 집이 최고지.",
    description: "차가운 보석이 깊은 물속에 있는 사주야. 지적이고 깊은 생각을 좋아하거든. 사람을 싫어하는 게 아니라 에너지 충전을 혼자 하는 타입이야. 근데 너무 혼자만 있다 보면 세상이 좁아질 수 있어.",
    catchpoint: "금음(辛) + 수(亥) = 보석이 깊은 물속에 → 혼자만의 세계에서 충전",
    bestMatch: "병자-f",
    worstMatch: "병오-m",
    rarity: 3,
  },

  // ── 19. 임진 (壬辰) 여성 — 수(양) + 토 ──
  {
    id: "임진-f",
    ilju: "임진",
    hanja: "壬辰",
    gender: "female",
    name: "떠들썩한 맏언니",
    emoji: "🌊",
    tagline: "정신 없는데 없으면 허전함",
    stemElement: "수(水)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-pink",
    strengths: ["사교성", "추진력", "의리"],
    weaknesses: ["오지랖", "감수성이 풍부함"],
    quote: "야 내가 해줄게. 가만히 있어.",
    description: "큰 물이 땅 위를 휩쓸고 가는 사주야. 에너지가 넘치고 사람 챙기기를 좋아하거든. 모임에서 제일 시끄러운데, 막상 없으면 '왜 이렇게 조용하지?' 하게 되는 타입이야.",
    catchpoint: "수양(壬) + 토(辰) = 큰 물이 땅을 휩씀 → 에너지+사교성, 없으면 허전",
    bestMatch: "정묘-m",
    worstMatch: "기미-m",
    rarity: 3,
  },

  // ── 20. 계유 (癸酉) 남성 — 수(음) + 금 ──
  {
    id: "계유-m",
    ilju: "계유",
    hanja: "癸酉",
    gender: "male",
    name: "프로생각러",
    emoji: "🧊",
    tagline: "머릿속에 물음표 오만개",
    stemElement: "수(水)",
    branchElement: "금(金)",
    yinyang: "음(陰)",
    tagColor: "bg-lavender",
    strengths: ["분석력", "신중함", "직관"],
    weaknesses: ["걱정 과다", "실행 느림"],
    quote: "근데 그거 진짜 괜찮은 거 맞아...?",
    description: "차가운 물이 금속을 타고 흐르는 사주야. 머리가 정말 좋은데 그만큼 생각이 많거든. '이렇게 하면 저렇게 되고, 저렇게 되면...' 끝없이 시뮬레이션 돌리는 타입이야. 가끔은 생각을 멈추고 일단 해보는 것도 답이야.",
    catchpoint: "수음(癸) + 금(酉) = 물이 금속을 타고 흐름 → 머리 좋은 만큼 생각 과다",
    bestMatch: "무오-f",
    worstMatch: "병오-m",
    rarity: 3,
  },

  // ── 21. 갑오 (甲午) 여성 — 목(양) + 화 ──
  {
    id: "갑오-f",
    ilju: "갑오",
    hanja: "甲午",
    gender: "female",
    name: "꽂히면 직진",
    emoji: "🏇",
    tagline: "관심 없으면 0%, 꽂히면 200%",
    stemElement: "목(木)",
    branchElement: "화(火)",
    yinyang: "양(陽)",
    tagColor: "bg-neon-green",
    strengths: ["집중력", "열정", "추진력"],
    weaknesses: ["관심 밖은 방치", "번아웃"],
    quote: "이건 내 거야. 다 비켜.",
    description: "나무가 불을 만나서 활활 타는 사주야. 뭔가 꽂히면 진짜 무섭게 몰입하거든. 근데 관심 없는 건 진짜 눈에 안 들어오는 게 함정이야. 온도차가 좀 있는 편인데, 그게 또 매력이기도 해.",
    catchpoint: "목양(甲) + 화(午) = 나무가 불을 만남 → 꽂히면 활활, 관심 밖은 0도",
    bestMatch: "계유-m",
    worstMatch: "경오-f",
    rarity: 4,
  },

  // ── 22. 을사 (乙巳) 남성 — 목(음) + 화 ──
  {
    id: "을사-m",
    ilju: "을사",
    hanja: "乙巳",
    gender: "male",
    name: "소프트 카리스마",
    emoji: "🌹",
    tagline: "정신 차리면 따라가고 있음",
    stemElement: "목(木)",
    branchElement: "화(火)",
    yinyang: "음(陰)",
    tagColor: "bg-neon-green",
    strengths: ["설득력", "매력", "교양"],
    weaknesses: ["우회적", "결정 느림"],
    quote: "내 말이 맞지? 맞잖아? ㅎㅎ",
    description: "작은 풀이 불꽃과 함께 있는 사주야. 강하게 밀어붙이는 스타일은 아닌데 은근히 주변을 움직이는 힘이 있어. '이 사람 말이면 해볼까'라는 생각이 드는 타입이거든.",
    catchpoint: "목음(乙) + 화(巳) = 풀이 불꽃과 함께 → 세게 안 밀어도 은근히 따라감",
    bestMatch: "경오-f",
    worstMatch: "신유-m",
    rarity: 3,
  },

  // ── 23. 병신 (丙申) 여성 — 화(양) + 금 ──
  {
    id: "병신-f",
    ilju: "병신",
    hanja: "丙申",
    gender: "female",
    name: "미친 실행력",
    emoji: "⚡",
    tagline: "스페이스 X보다 우주 먼저 갈 거 같음",
    stemElement: "화(火)",
    branchElement: "금(金)",
    yinyang: "양(陽)",
    tagColor: "bg-pop-orange",
    strengths: ["실행력", "순발력", "효율"],
    weaknesses: ["인내심 부족", "중간에 바꿈"],
    quote: "그거 언제 한다고? 나 벌써 했는데.",
    description: "불이 쇠를 녹이는 사주야. 생각하면 바로 실행하는 스피드가 장점이거든. '내일 하지 뭐'가 사전에 없어. 근데 빨리 시작하는 만큼 빨리 질릴 수도 있어서, 끝까지 가는 연습도 필요해.",
    catchpoint: "화양(丙) + 금(申) = 불이 쇠를 녹임 → 생각→실행 즉시, 스피드 특화",
    bestMatch: "임진-m",
    worstMatch: "기미-m",
    rarity: 4,
  },

  // ── 24. 정유 (丁酉) 남성 — 화(음) + 금 ──
  {
    id: "정유-m",
    ilju: "정유",
    hanja: "丁酉",
    gender: "male",
    name: "세심보스",
    emoji: "🔍",
    tagline: "다 놓쳤는데 혼자 발견함",
    stemElement: "화(火)",
    branchElement: "금(金)",
    yinyang: "음(陰)",
    tagColor: "bg-pop-orange",
    strengths: ["디테일", "심미안", "정확함"],
    weaknesses: ["예민함", "스트레스 잘 받음"],
    quote: "아 그거 2mm 틀어졌는데.",
    description: "작은 불꽃이 금속을 세밀하게 다듬는 사주야. 남들이 '뭐가 다르지?' 하는 걸 바로 잡아내거든. 디자인, 글, 음식 뭐든 퀄리티에 예민해. 근데 그만큼 스트레스도 잘 받으니까 적당히 눈 감는 연습도 필요해.",
    catchpoint: "화음(丁) + 금(酉) = 작은 불이 금속을 세밀하게 다듬 → 디테일 극강",
    bestMatch: "임진-f",
    worstMatch: "무오-m",
    rarity: 3,
  },

  // ── 25. 무자 (戊子) 여성 — 토(양) + 수 ──
  {
    id: "무자-f",
    ilju: "무자",
    hanja: "戊子",
    gender: "female",
    name: "겉은 차분 속은 야생",
    emoji: "🐺",
    tagline: "*주의* 웃다가 물 수 있음",
    stemElement: "토(土)",
    branchElement: "수(水)",
    yinyang: "양(陽)",
    tagColor: "bg-mustard",
    strengths: ["내면의 힘", "참을성", "반전"],
    weaknesses: ["참다가 한번에 터짐", "속으로 담아두는 편"],
    quote: "참고 참고 참다가... 터졌다.",
    description: "단단한 땅 아래에 물이 흐르는 사주야. 평소에는 진짜 차분한데, 선을 넘으면 한방에 터지거든. 주변에서 '갑자기 왜 저래?' 하는데 사실 오래전부터 참고 있었던 거야. 작을 때 말하는 습관을 들이면 좋아.",
    catchpoint: "토양(戊) + 수(子) = 단단한 땅 아래 물 → 평소 차분한데 선 넘으면 폭발",
    bestMatch: "을사-m",
    worstMatch: "병자-m",
    rarity: 3,
  },

  // ── 26. 경인 (庚寅) 남성 — 금(양) + 목 ──
  {
    id: "경인-m",
    ilju: "경인",
    hanja: "庚寅",
    gender: "male",
    name: "승부욕 만렙",
    emoji: "🥊",
    tagline: "지는 거 못 참음",
    stemElement: "금(金)",
    branchElement: "목(木)",
    yinyang: "양(陽)",
    tagColor: "bg-charcoal",
    strengths: ["경쟁심", "도전정신", "자기관리"],
    weaknesses: ["결과에 예민함", "목표 의식이 강함"],
    quote: "2등은 의미 없어.",
    description: "날카로운 쇠가 나무를 만난 사주야. 자르고 깎아내는 힘이 있어서 경쟁에서 강하거든. 운동이든 일이든 이기고 싶은 마음이 진짜 커. 근데 가끔 남이랑 비교하느라 정작 본인이 얼마나 잘하고 있는지를 못 볼 때가 있어.",
    catchpoint: "금양(庚) + 목(寅) = 쇠가 나무를 깎음 → 경쟁에서 지는 걸 못 참음",
    bestMatch: "을묘-f",
    worstMatch: "갑인-f",
    rarity: 4,
  },

  // ── 27. 신축 (辛丑) 여성 — 금(음) + 토 ──
  {
    id: "신축-f",
    ilju: "신축",
    hanja: "辛丑",
    gender: "female",
    name: "슬로우 스타터",
    emoji: "💍",
    tagline: "결국 마지막에 결과 들고 옴",
    stemElement: "금(金)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-lavender",
    strengths: ["꼼꼼함", "신뢰", "묵묵함"],
    weaknesses: ["융통성 부족", "원칙에 충실"],
    quote: "제대로 안 할 거면 안 하는 게 나아.",
    description: "보석이 흙 속에 묻혀 있는 사주야. 겉으로 화려하진 않은데 시간이 지나면 진가가 드러나는 타입이거든. '이 사람 별로인 줄 알았는데 진짜 괜찮다'는 말을 뒤늦게 듣는 스타일이야.",
    catchpoint: "금음(辛) + 토(丑) = 보석이 흙 속에 묻힘 → 시간 지나야 진가 드러남",
    bestMatch: "병오-m",
    worstMatch: "갑오-f",
    rarity: 2,
  },

  // ── 28. 임술 (壬戌) 남성 — 수(양) + 토 ──
  {
    id: "임술-m",
    ilju: "임술",
    hanja: "壬戌",
    gender: "male",
    name: "한 끗 차이 천재",
    emoji: "🧠",
    tagline: "첨엔 '뭔 소리야?' 했는데 납득됨",
    stemElement: "수(水)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-pink",
    strengths: ["창의력", "직관", "아이디어"],
    weaknesses: ["이상이 높은 편", "마무리 약함"],
    quote: "이거 진짜 대박인데... 설명이 안 돼.",
    description: "물이 땅과 부딪히는 사주야. 아이디어가 진짜 끝없이 나오거든. 근데 10개 생각하면 7개는 천재적이고 3개는 '뭐라는 거지?' 인 게 특징이야. 아이디어를 실행까지 끌고 가는 힘을 기르면 진짜 무서워지는 타입이야.",
    catchpoint: "수양(壬) + 토(戌) = 물이 땅과 부딪힘 → 아이디어 폭발, 천재와 엉뚱 사이",
    bestMatch: "정해-f",
    worstMatch: "기사-m",
    rarity: 5,
  },

  // ── 29. 갑술 (甲戌) 여성 — 목(양) + 토 ──
  {
    id: "갑술-f",
    ilju: "갑술",
    hanja: "甲戌",
    gender: "female",
    name: "안 될 거 뭐 있어",
    emoji: "🦊",
    tagline: "왠지 모르겠는데 얘는 잘될 거 같음",
    stemElement: "목(木)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-neon-green",
    strengths: ["자신감", "긍정", "돌파력"],
    weaknesses: ["이상이 높은 편", "아쉬움이 오래감"],
    quote: "안 될 이유가 있어? 없잖아.",
    description: "큰 나무가 마른 땅 위에 서 있는 사주야. 조건이 안 좋은데도 '나는 될 거야'라는 확신이 있거든. 신기한 건 그 자신감대로 진짜 되는 경우가 많다는 거야. 근데 가끔 현실 체크는 해줘야 해.",
    catchpoint: "목양(甲) + 토(戌) = 나무가 마른 땅에 → 조건 안 좋아도 '된다'는 확신",
    bestMatch: "계유-m",
    worstMatch: "경오-f",
    rarity: 4,
  },

  // ── 30. 계축 (癸丑) 남성 — 수(음) + 토 ──
  {
    id: "계축-m",
    ilju: "계축",
    hanja: "癸丑",
    gender: "male",
    name: "묵묵한 실력파",
    emoji: "🐂",
    tagline: "말로 안 하고 결과로 보여줌",
    stemElement: "수(水)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-pink",
    strengths: ["실력", "성실", "뚝심"],
    weaknesses: ["자기 표현이 조용한 편", "칭찬 듣고 싶지만 티 안 냄"],
    quote: "... (결과물을 내밀며)",
    description: "작은 물이 단단한 땅 속으로 스며드는 사주야. 말이 많은 타입은 아닌데 일을 시키면 묵묵히 해내거든. 주변에서 '이 사람 실력 있다'는 걸 나중에야 알게 되는 타입이야. 가끔은 본인 잘한 것도 좀 말해도 돼.",
    catchpoint: "수음(癸) + 토(丑) = 물이 땅속으로 스며듦 → 말 없이 실력으로 증명",
    bestMatch: "병자-f",
    worstMatch: "갑오-f",
    rarity: 2,
  },

  // ── 31. 갑자 (甲子) 여성 — 목(양) + 수 ──
  {
    id: "갑자-f",
    ilju: "갑자",
    hanja: "甲子",
    gender: "female",
    name: "생각은 나중에",
    emoji: "🚀",
    tagline: "준비 80%면 이미 뛰고 있음",
    stemElement: "목(木)",
    branchElement: "수(水)",
    yinyang: "양(陽)",
    tagColor: "bg-neon-green",
    strengths: ["결단력", "자립심", "위기 대처"],
    weaknesses: ["내 생각에 확신이 강함", "지나친 독립"],
    quote: "기다리면 타이밍 놓쳐.",
    description: "큰 나무가 깊은 물 위에서 자라는 사주야. 남자 갑자가 '불도저'라면, 여자 갑자는 방향을 정하면 혼자서 쓱 출발해 있는 타입이야. 누가 말려도 '내가 알아서 해'가 기본 모드거든. 근데 가끔 혼자 너무 멀리 가서 뒤돌아보면 아무도 없을 때가 있어.",
    catchpoint: "목양(甲) + 수(子) = 물 받은 큰 나무 → 혼자 성장 가능한 자립형, 기다림이 없음",
    bestMatch: "기미-m",
    worstMatch: "경진-m",
    rarity: 3,
  },

  // ── 32. 을묘 (乙卯) 남성 — 목(음) + 목 ──
  {
    id: "을묘-m",
    ilju: "을묘",
    hanja: "乙卯",
    gender: "male",
    name: "분위기 설계자",
    emoji: "🎨",
    tagline: "이 사람이 고른 카페는 다 분위기 맛집",
    stemElement: "목(木)",
    branchElement: "목(木)",
    yinyang: "음(陰)",
    tagColor: "bg-lavender",
    strengths: ["심미안", "분위기 메이킹", "섬세함"],
    weaknesses: ["신중한 선택", "이상이 높은 편"],
    quote: "아니 거기 가면 안 돼, 여긴 가야 돼.",
    description: "꽃밭에 피어난 꽃 사주라 미적 감각이 장난 아니야. 여자 을묘가 '느끼는 사람'이라면, 남자 을묘는 느낀 걸 공간이나 상황으로 세팅하는 타입이야. 데이트 코스든 플레이리스트든 이 사람이 짜면 분위기가 달라져.",
    catchpoint: "목음(乙) + 목(卯) = 꽃이 꽃밭에 핌 → 감수성이 '세팅 능력'으로 발현",
    bestMatch: "경오-f",
    worstMatch: "경인-m",
    rarity: 2,
  },

  // ── 33. 병오 (丙午) 여성 — 화(양) + 화 ──
  {
    id: "병오-f",
    ilju: "병오",
    hanja: "丙午",
    gender: "female",
    name: "인간 비타민",
    emoji: "🌟",
    tagline: "만나고 오면 배터리 한 칸 채워짐",
    stemElement: "화(火)",
    branchElement: "화(火)",
    yinyang: "양(陽)",
    tagColor: "bg-pop-orange",
    strengths: ["긍정 에너지", "분위기 전환", "자신감"],
    weaknesses: ["오버 경향", "감정 표현이 클 때 있음"],
    quote: "우울해? 나랑 밥 먹으러 가자 당장.",
    description: "화(火) 두 겹이라 에너지가 진짜 넘쳐. 남자 병오가 '주인공 체질'이라면, 여자 병오는 그 에너지를 주변한테 쏟아붓는 스타일이야. 이 사람이랑 밥 한 끼 먹으면 기분이 올라가거든. 근데 본인이 지쳤을 때도 밝은 척하다가 갑자기 꺼질 수 있어.",
    catchpoint: "화양(丙) + 화(午) = 불 두 겹 → 넘치는 에너지를 남한테 나눠주는 방향으로 발현",
    bestMatch: "임오-m",
    worstMatch: "신유-m",
    rarity: 4,
  },

  // ── 34. 경진 (庚辰) 여성 — 금(양) + 토 ──
  {
    id: "경진-f",
    ilju: "경진",
    hanja: "庚辰",
    gender: "female",
    name: "피드백 맛집",
    emoji: "🪓",
    tagline: "팩트로 때리는데 영양제임",
    stemElement: "금(金)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-charcoal",
    strengths: ["객관성", "조언력", "신뢰감"],
    weaknesses: ["말이 직접적", "이성적이라 차가워 보임"],
    quote: "다 너 잘되라고 하는 말인거 알지?",
    description: "단단한 쇠가 산 위에 있는 사주야. 남자 경진이 '중꺾마'로 자기한테 집중한다면, 여자 경진은 그 단단함으로 주변한테 진짜 필요한 말을 해주는 타입이야. 당장은 아플 수 있는데 결국 '그때 말해줘서 고마워'라는 말을 듣거든.",
    catchpoint: "금양(庚) + 토(辰) = 쇠가 산 위에 → 단단한 기준으로 솔직한 피드백 가능",
    bestMatch: "을묘-m",
    worstMatch: "을해-m",
    rarity: 3,
  },

  // ── 35. 임오 (壬午) 남성 — 수(양) + 화 ──
  {
    id: "임오-m",
    ilju: "임오",
    hanja: "壬午",
    gender: "male",
    name: "온도 조절 실패",
    emoji: "🌡️",
    tagline: "관심 없는 척하다가 제일 진심임",
    stemElement: "수(水)",
    branchElement: "화(火)",
    yinyang: "양(陽)",
    tagColor: "bg-pink",
    strengths: ["순발력", "감정 깊이", "반전 매력"],
    weaknesses: ["일관성 부족", "감수성이 풍부함"],
    quote: "별로 관심 없었는데... 어? 왜 이러지 나.",
    description: "물 위에 불이 있는 사주야. 여자 임오가 '츤데레 본체'라면, 남자 임오는 본인도 모르게 온도가 왔다갔다 하는 타입이야. 갑자기 관심 폭발했다가 다음 날 아무렇지 않은 것처럼 굴거든. 본인도 왜 그런지 모를 때가 있어.",
    catchpoint: "수양(壬) + 화(午) = 물 위에 불 → 온도차가 본인도 통제 불가",
    bestMatch: "병오-f",
    worstMatch: "무진-f",
    rarity: 4,
  },

  // ── 36. 정해 (丁亥) 남성 — 화(음) + 수 ──
  {
    id: "정해-m",
    ilju: "정해",
    hanja: "丁亥",
    gender: "male",
    name: "말 안 해도 아는 형",
    emoji: "🔮",
    tagline: "말보다 눈치가 먼저 움직임",
    stemElement: "화(火)",
    branchElement: "수(水)",
    yinyang: "음(陰)",
    tagColor: "bg-pop-orange",
    strengths: ["상황 판단", "조용한 배려", "깊은 공감"],
    weaknesses: ["말 아끼다 오해 받음", "번아웃"],
    quote: "커피 사왔어. 힘들어 보여서.",
    description: "바다 위 촛불 사주야. 여자 정해가 '눈치 만렙'으로 읽어내는 데 집중한다면, 남자 정해는 읽은 걸 행동으로 조용히 풀어내는 타입이야. 말 한마디 없이 필요한 걸 챙겨주거든. 근데 본인한테 필요한 건 남한테 말 못 하는 게 문제야.",
    catchpoint: "화음(丁) + 수(亥) = 바다 위 촛불 → 읽은 걸 행동으로 표현, 조용한 케어",
    bestMatch: "임진-f",
    worstMatch: "계사-f",
    rarity: 3,
  },

  // ── 37. 무진 (戊辰) 남성 — 토(양) + 토 ──
  {
    id: "무진-m",
    ilju: "무진",
    hanja: "戊辰",
    gender: "male",
    name: "오뚝이 멘탈",
    emoji: "🏔️",
    tagline: "다들 난린데 혼자 평온함",
    stemElement: "토(土)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-mustard",
    strengths: ["위기 대처", "담대함", "안정감"],
    weaknesses: ["여유 있는 반응", "익숙한 방식 선호"],
    quote: "다들 왜 그래? 괜찮을 건데.",
    description: "토(土)가 두 겹이라 안정감이 남다른 사주야. 여자 무진이 '걱정 삭제 담당'으로 주변을 편하게 해준다면, 남자 무진은 위기 상황에서 혼자 멀쩡한 타입이야. 팀 프로젝트 터져도 '어 그래? 고치면 되지' 하는 사람이거든. 근데 가끔 너무 안 흔들려서 공감이 부족해 보일 수 있어.",
    catchpoint: "토양(戊) + 토(辰) = 흙 두 겹 → 위기에도 안 흔들리는 멘탈, 둔감력 특화",
    bestMatch: "계사-f",
    worstMatch: "임오-f",
    rarity: 2,
  },

  // ── 38. 신유 (辛酉) 여성 — 금(음) + 금 ──
  {
    id: "신유-f",
    ilju: "신유",
    hanja: "辛酉",
    gender: "female",
    name: "호불호 명확러",
    emoji: "👛",
    tagline: "추천했다가 평생 따라다니게 됨",
    stemElement: "금(金)",
    branchElement: "금(金)",
    yinyang: "음(陰)",
    tagColor: "bg-lavender",
    strengths: ["안목", "큐레이션 능력", "자기 확신"],
    weaknesses: ["원칙을 중시함", "취향이 확고함"],
    quote: "그건 좀... 아닌데... 이거 써봐.",
    description: "금(金)이 두 겹이라 기준이 확고한 사주야. 남자 신유가 '아무거나 불가'로 못 정하는 느낌이라면, 여자 신유는 확실히 아는 거야. 뭐가 좋은지. 그래서 주변에서 추천을 많이 받거든. 근데 본인 기준에 안 맞는 건 진짜 입에 안 대.",
    catchpoint: "금음(辛) + 금(酉) = 보석이 보석 위에 → 기준이 확고해서 큐레이터 기질",
    bestMatch: "병자-m",
    worstMatch: "을해-m",
    rarity: 4,
  },

  // ── 39. 계사 (癸巳) 남성 — 수(음) + 화 ──
  {
    id: "계사-m",
    ilju: "계사",
    hanja: "癸巳",
    gender: "male",
    name: "시나리오 작가",
    emoji: "🎯",
    tagline: "앞에 안 나서는데 결국 얘 뜻대로 됨",
    stemElement: "수(水)",
    branchElement: "화(火)",
    yinyang: "음(陰)",
    tagColor: "bg-charcoal",
    strengths: ["전략", "설계력", "인내"],
    weaknesses: ["신뢰 어려움", "과도한 계산"],
    quote: "나? 난 아무것도 안 했는데?",
    description: "작은 물이 불꽃 위를 흐르는 사주야. 여자 계사가 '조용한 승부사'로 정면 돌파한다면, 남자 계사는 아예 뒤에서 판을 설계하는 타입이야. 직접 나서지 않는데 결과가 이 사람이 원하는 방향으로 흘러가거든. 참모형 인재인데, 너무 혼자 계산하면 외로워질 수 있어.",
    catchpoint: "수음(癸) + 화(巳) = 물이 불 위를 흐름 → 드러나지 않는 설계형 전략가",
    bestMatch: "무진-f",
    worstMatch: "정해-f",
    rarity: 5,
  },

  // ── 40. 기미 (己未) 여성 — 토(음) + 토 ──
  {
    id: "기미-f",
    ilju: "기미",
    hanja: "己未",
    gender: "female",
    name: "위로 충전소",
    emoji: "☕",
    tagline: "떠들다 보면 내가 답 찾고 있음",
    stemElement: "토(土)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-mustard",
    strengths: ["경청", "안정감", "공감력"],
    weaknesses: ["본인 우선순위 뒤로 밀림", "거절 못함"],
    quote: "응, 응, 그래서? 다 말해봐.",
    description: "따뜻한 흙이 두 겹인 사주야. 남자 기미가 '마이페이스 힐러'로 느리지만 결국 해내는 타입이라면, 여자 기미는 들어주는 것 자체가 힘인 사람이야. 이 사람한테 고민 털어놓으면 조언 안 해도 왜인지 정리가 돼. 근데 남의 고민만 받다가 본인 에너지가 바닥날 수 있어.",
    catchpoint: "토음(己) + 토(未) = 따뜻한 흙 두 겹 → 수용력 극대화, 들어주는 것 자체가 치유",
    bestMatch: "갑자-m",
    worstMatch: "경인-m",
    rarity: 2,
  },

  // ── 41. 갑인 (甲寅) 남성 — 목(양) + 목 ──
  {
    id: "갑인-m",
    ilju: "갑인",
    hanja: "甲寅",
    gender: "male",
    name: "인간 방패막",
    emoji: "🐯",
    tagline: "평소엔 쿨한데 선 넘으면 돌변함",
    stemElement: "목(木)",
    branchElement: "목(木)",
    yinyang: "양(陽)",
    tagColor: "bg-neon-green",
    strengths: ["의리", "보호 본능", "결단력"],
    weaknesses: ["감정 표현이 클 때 있음", "이분법적 판단"],
    quote: "평소엔 다 좋아. 근데 선 넘진 마.",
    description: "큰 나무가 호랑이 위에 앉은 사주야. 여자 갑인이 '못 참는 정의파'로 매번 나선다면, 남자 갑인은 평소엔 쿨한데 진짜 선을 넘는 순간 사람이 달라지는 타입이야. 내 사람 건드리면 끝장을 보거든. 근데 한번 등 돌리면 돌이키기 어려워.",
    catchpoint: "목양(甲) + 목(寅) = 나무+호랑이 → 보호 본능 강한 호랑이형, 선 넘으면 폭발",
    bestMatch: "기미-f",
    worstMatch: "경진-f",
    rarity: 3,
  },

  // ── 42. 을해 (乙亥) 여성 — 목(음) + 수 ──
  {
    id: "을해-f",
    ilju: "을해",
    hanja: "乙亥",
    gender: "female",
    name: "사람 수집가",
    emoji: "🦋",
    tagline: "나가면 인사하기 바쁨",
    stemElement: "목(木)",
    branchElement: "수(水)",
    yinyang: "음(陰)",
    tagColor: "bg-neon-green",
    strengths: ["네트워킹", "친화력", "유연함"],
    weaknesses: ["깊은 관계 어려움", "본심 숨김"],
    quote: "아 그 사람? 나 아는 사람인데!",
    description: "작은 풀이 물 위에서 흘러가는 사주야. 남자 을해가 '분위기 맞춤러'로 스며든다면, 여자 을해는 스며드는 걸 넘어서 인맥을 엮는 타입이야. 어디를 가든 아는 사람이 있고, 사람과 사람을 연결해주는 능력이 있거든. 근데 넓은 만큼 깊이가 부족할 수 있어.",
    catchpoint: "목음(乙) + 수(亥) = 풀이 물 위에 → 흘러가면서 만나는 인연을 다 엮는 연결형",
    bestMatch: "병오-m",
    worstMatch: "신유-f",
    rarity: 2,
  },

  // ── 43. 병자 (丙子) 남성 — 화(양) + 수 ──
  {
    id: "병자-m",
    ilju: "병자",
    hanja: "丙子",
    gender: "male",
    name: "회복력 치트키",
    emoji: "🔥",
    tagline: "망해도 다음 날 또 뭔가 시작함",
    stemElement: "화(火)",
    branchElement: "수(水)",
    yinyang: "양(陽)",
    tagColor: "bg-pop-orange",
    strengths: ["회복력", "긍정", "도전정신"],
    weaknesses: ["도전이 과할 때", "같은 패턴 반복"],
    quote: "어제 망했거든? 근데 오늘 새로운 거 찾았어.",
    description: "불이 물 위에서 타는 사주야. 여자 병자가 '열정 과부하'로 동시에 다 하고 싶다면, 남자 병자는 실패해도 안 꺼지는 게 핵심이야. 사업을 세 번 말아도 네 번째를 시작하는 타입이거든. 이 회복력이 진짜 무서운 무기인데, 가끔은 왜 망했는지 복기를 해야 해.",
    catchpoint: "화양(丙) + 수(子) = 불이 물 위에서 탐 → 물이 꺼뜨려도 다시 타오르는 회복력",
    bestMatch: "신유-f",
    worstMatch: "임오-f",
    rarity: 3,
  },

  // ── 44. 정묘 (丁卯) 여성 — 화(음) + 목 ──
  {
    id: "정묘-f",
    ilju: "정묘",
    hanja: "丁卯",
    gender: "female",
    name: "몰입 중독러",
    emoji: "🌙",
    tagline: "한 번 꽂히면 온 세상이 그거임",
    stemElement: "화(火)",
    branchElement: "목(木)",
    yinyang: "음(陰)",
    tagColor: "bg-pop-orange",
    strengths: ["몰입력", "감성", "충성도"],
    weaknesses: ["한번 빠지면 오래감", "관심 분야 집중형"],
    quote: "이거 진짜 좋은데 너도 한번만 봐봐... 제발...",
    description: "작은 불꽃이 나무를 만나서 타는 사주야. 남자 정묘가 '은근 중독되는 사람'으로 타인을 끌어당긴다면, 여자 정묘는 본인이 뭔가에 중독되는 타입이야. 사람이든 취미든 한번 꽂히면 그것밖에 안 보이거든. 그 몰입이 강점인데 가끔은 거리 두는 연습도 필요해.",
    catchpoint: "화음(丁) + 목(卯) = 촛불+나무 → 타오르면 연료가 있어서 안 꺼짐, 몰입형",
    bestMatch: "임술-m",
    worstMatch: "계유-m",
    rarity: 3,
  },

  // ── 45. 무오 (戊午) 남성 — 토(양) + 화 ──
  {
    id: "무오-m",
    ilju: "무오",
    hanja: "戊午",
    gender: "male",
    name: "든든한 서포터",
    emoji: "🧹",
    tagline: "없으면 빈자리 확 느껴짐",
    stemElement: "토(土)",
    branchElement: "화(火)",
    yinyang: "양(陽)",
    tagColor: "bg-mustard",
    strengths: ["책임감", "마무리 능력", "뚝심"],
    weaknesses: ["티를 안 내는 편", "티 안 냄"],
    quote: "됐어, 나머지는 내가 처리할게.",
    description: "흙이 불 위에 앉은 사주야. 여자 무오가 '엄마 같은 보스'로 이끌면서 챙긴다면, 남자 무오는 누가 시작한 일의 뒷정리를 도맡는 타입이야. 팀에서 화려한 포지션은 아닌데 이 사람 빠지면 모든 게 어긋나거든. 가끔 '나도 앞에 서고 싶다' 말해도 돼.",
    catchpoint: "토양(戊) + 화(午) = 흙이 불 위에 → 열기(성과)를 받쳐주는 기반, 마무리 특화",
    bestMatch: "갑오-f",
    worstMatch: "갑인-f",
    rarity: 2,
  },

  // ── 46. 기사 (己巳) 여성 — 토(음) + 화 ──
  {
    id: "기사-f",
    ilju: "기사",
    hanja: "己巳",
    gender: "female",
    name: "웃는 얼굴의 승부사",
    emoji: "🎀",
    tagline: "목소리 안 높이고 다 가져감",
    stemElement: "토(土)",
    branchElement: "화(火)",
    yinyang: "음(陰)",
    tagColor: "bg-mustard",
    strengths: ["설득력", "전략적 관계", "인내"],
    weaknesses: ["속내 안 보여줌", "전략적으로 보일 때"],
    quote: "어머~ 고마워~ (계획대로)",
    description: "부드러운 흙 속에 불이 숨어있는 사주야. 남자 기사가 '겉은 순둥 속은 야망'으로 때를 기다린다면, 여자 기사는 부드럽게 웃으면서 원하는 걸 얻어내는 타입이야. 정면 돌파 대신 관계를 활용하거든. 영리한 건 맞는데, 진심을 보여줘야 할 때는 보여줘야 해.",
    catchpoint: "토음(己) + 화(巳) = 부드러운 흙 속 불 → 부드러운 겉면을 활용한 전략형",
    bestMatch: "갑자-m",
    worstMatch: "경오-m",
    rarity: 4,
  },

  // ── 47. 경오 (庚午) 남성 — 금(양) + 화 ──
  {
    id: "경오-m",
    ilju: "경오",
    hanja: "庚午",
    gender: "male",
    name: "할 말은 하는 형",
    emoji: "🦁",
    tagline: "아픈데 듣고 보면 맞말임",
    stemElement: "금(金)",
    branchElement: "화(火)",
    yinyang: "양(陽)",
    tagColor: "bg-charcoal",
    strengths: ["정직함", "추진력", "원칙"],
    weaknesses: ["표현이 직접적", "오해 사기 쉬움"],
    quote: "그거 왜 해? 의미 없잖아.",
    description: "쇠가 불 속에서 달궈지는 사주야. 여자 경오가 '칼 같은 사람'으로 할 말 하는 스타일이라면, 남자 경오는 아예 돌려 말하는 기능이 없어. '무의미한 거 왜 해?'를 회의 때 진짜 말하는 타입이거든. 그래서 적이 많은데 진짜 편도 많아.",
    catchpoint: "금양(庚) + 화(午) = 쇠가 불에 달궈짐 → 날카로움이 직설로 발현, 돌려말 불가",
    bestMatch: "을해-f",
    worstMatch: "기사-f",
    rarity: 4,
  },

  // ── 48. 신해 (辛亥) 여성 — 금(음) + 수 ──
  {
    id: "신해-f",
    ilju: "신해",
    hanja: "辛亥",
    gender: "female",
    name: "혼자도 럭셔리",
    emoji: "🌌",
    tagline: "취미 3개에 혼밥 맛집 리스트 있음",
    stemElement: "금(金)",
    branchElement: "수(水)",
    yinyang: "음(陰)",
    tagColor: "bg-lavender",
    strengths: ["자기만족", "취미 부자", "감성 풍부"],
    weaknesses: ["거리 두기 경향", "마음 여는 데 시간 걸림"],
    quote: "오늘 혼영하고 혼카페 하려고~",
    description: "보석이 깊은 물속에 있는 사주야. 남자 신해가 '충전은 혼자서' 하는 타입이라면, 여자 신해는 아예 혼자의 세계가 풍요로운 사람이야. 혼밥, 혼영, 혼여행 다 즐기고, 취미도 많아서 외롭지 않거든. 근데 가끔은 누군가를 들여보내는 것도 괜찮아.",
    catchpoint: "금음(辛) + 수(亥) = 보석이 깊은 물속에 → 혼자의 세계가 완성형, 풍요로운 솔로",
    bestMatch: "병자-m",
    worstMatch: "병오-m",
    rarity: 3,
  },

  // ── 49. 임진 (壬辰) 남성 — 수(양) + 토 ──
  {
    id: "임진-m",
    ilju: "임진",
    hanja: "壬辰",
    gender: "male",
    name: "분위기 장악러",
    emoji: "🎤",
    tagline: "입 열면 자동으로 집중하게 됨",
    stemElement: "수(水)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-pink",
    strengths: ["화술", "장악력", "추진력"],
    weaknesses: ["쉬는 타이밍 놓침", "의견이 분명함"],
    quote: "자, 들어봐. 내가 정리해줄게.",
    description: "큰 물이 땅 위를 휩쓸고 가는 사주야. 여자 임진이 '떠들썩한 맏언니'로 시끄럽게 챙긴다면, 남자 임진은 말 한마디로 분위기를 잡는 타입이야. 회의에서 정리 발언하면 다 고개 끄덕이는 그 사람이거든. 근데 남의 말도 좀 끝까지 들어줘야 해.",
    catchpoint: "수양(壬) + 토(辰) = 큰 물이 땅을 휩씀 → 에너지가 화술+장악력으로 발현",
    bestMatch: "정묘-f",
    worstMatch: "기미-f",
    rarity: 3,
  },

  // ── 50. 계유 (癸酉) 여성 — 수(음) + 금 ──
  {
    id: "계유-f",
    ilju: "계유",
    hanja: "癸酉",
    gender: "female",
    name: "호기심 대마왕",
    emoji: "🪞",
    tagline: "한 번 궁금하면 끝을 봄",
    stemElement: "수(水)",
    branchElement: "금(金)",
    yinyang: "음(陰)",
    tagColor: "bg-lavender",
    strengths: ["통찰력", "본질 파악", "논리력"],
    weaknesses: ["오버씽킹", "결정 미루기"],
    quote: "근데 진짜 왜 그런 거야? 원인이 뭔데?",
    description: "차가운 물이 금속을 타고 흐르는 사주야. 남자 계유가 '프로생각러'로 시뮬레이션을 돌린다면, 여자 계유는 생각이 많은 게 아니라 깊은 거야. 표면에서 안 멈추고 '왜?'를 계속 파거든. 그래서 본질을 잘 잡는데, 너무 깊이 들어가면 결정을 못 내릴 때가 있어.",
    catchpoint: "수음(癸) + 금(酉) = 물이 금속을 타고 흐름 → 생각의 방향이 '넓이'가 아닌 '깊이'",
    bestMatch: "무오-m",
    worstMatch: "병오-f",
    rarity: 3,
  },

  // ── 51. 갑오 (甲午) 남성 — 목(양) + 화 ──
  {
    id: "갑오-m",
    ilju: "갑오",
    hanja: "甲午",
    gender: "male",
    name: "폭발적 존재감",
    emoji: "🎆",
    tagline: "칭찬에 춤추는 대왕고래",
    stemElement: "목(木)",
    branchElement: "화(火)",
    yinyang: "양(陽)",
    tagColor: "bg-neon-green",
    strengths: ["퍼포먼스", "에너지", "주목도"],
    weaknesses: ["칭찬에 약함", "관심을 먹고 사는 타입"],
    quote: "봐봐! 이거 내가 한 거야!",
    description: "나무가 불을 만나 활활 타는 사주야. 여자 갑오가 '불 붙으면 끝장러'로 몰입 집중한다면, 남자 갑오는 불이 관객을 향해 타오르는 타입이야. 누가 봐주면 에너지가 200% 되거든. 근데 아무도 안 봐주면 급격히 시무룩해지는 게 함정이야.",
    catchpoint: "목양(甲) + 화(午) = 나무가 불을 만남 → 에너지가 밖으로 향함, 관객이 필요한 퍼포머",
    bestMatch: "계유-f",
    worstMatch: "신축-f",
    rarity: 4,
  },

  // ── 52. 을사 (乙巳) 여성 — 목(음) + 화 ──
  {
    id: "을사-f",
    ilju: "을사",
    hanja: "乙巳",
    gender: "female",
    name: "부드러운 한 방",
    emoji: "🌺",
    tagline: "부드럽게 말하는데 결론은 안 바뀜",
    stemElement: "목(木)",
    branchElement: "화(火)",
    yinyang: "음(陰)",
    tagColor: "bg-neon-green",
    strengths: ["설득력", "은근한 주도권", "매력"],
    weaknesses: ["돌려서 표현함", "진심 감춤"],
    quote: "어떻게 할지 네가 정해~ (이미 답 정해둠)",
    description: "작은 풀이 불꽃과 함께 있는 사주야. 남자 을사가 '소프트 카리스마'로 자연스럽게 따라가게 한다면, 여자 을사는 선택지를 줬는데 결국 본인이 원하는 대로 되게 만드는 타입이야. 다 부드럽게 진행되는데 끝에 보면 '어? 이거 이 사람 뜻이었네?' 싶거든.",
    catchpoint: "목음(乙) + 화(巳) = 풀+불꽃 → 부드러운 겉모습 뒤의 은근한 주도력",
    bestMatch: "경오-m",
    worstMatch: "신유-f",
    rarity: 3,
  },

  // ── 53. 병신 (丙申) 남성 — 화(양) + 금 ──
  {
    id: "병신-m",
    ilju: "병신",
    hanja: "丙申",
    gender: "male",
    name: "말보다 빠른 손",
    emoji: "🛠️",
    tagline: "설명할 시간에 이미 하고 있음",
    stemElement: "화(火)",
    branchElement: "금(金)",
    yinyang: "양(陽)",
    tagColor: "bg-pop-orange",
    strengths: ["즉각 실행", "효율", "문제 해결"],
    weaknesses: ["결과 중심형", "성급한 판단"],
    quote: "됐고, 내가 그냥 할게.",
    description: "불이 쇠를 녹이는 사주야. 여자 병신이 '미친 실행력'으로 생각 즉시 시작한다면, 남자 병신은 남한테 설명할 시간에 본인이 해버리는 타입이야. 회의보다 행동이 빠르거든. 효율은 미쳤는데 가끔 팀한테 '왜 그렇게 했는지' 공유는 해줘야 해.",
    catchpoint: "화양(丙) + 금(申) = 불이 쇠를 녹임 → 녹이는 과정(설명)을 건너뛰고 결과 직행",
    bestMatch: "임진-f",
    worstMatch: "기미-f",
    rarity: 4,
  },

  // ── 54. 정유 (丁酉) 여성 — 화(음) + 금 ──
  {
    id: "정유-f",
    ilju: "정유",
    hanja: "丁酉",
    gender: "female",
    name: "엑셀 요정",
    emoji: "📊",
    tagline: "느낌 왔다더니 자료까지 들고 옴",
    stemElement: "화(火)",
    branchElement: "금(金)",
    yinyang: "음(陰)",
    tagColor: "bg-pop-orange",
    strengths: ["분석력", "논리적 설득", "정확도"],
    weaknesses: ["감정보다 효율 우선", "거리감 있어 보임"],
    quote: "느낌이 아니라 수치를 봐야지.",
    description: "작은 불꽃이 금속을 다듬는 사주야. 남자 정유가 '세심보스'로 디테일을 잡아낸다면, 여자 정유는 그 예민함을 데이터로 정리하는 타입이야. 감으로도 맞추는데 '감이잖아'라는 말을 싫어해서 꼭 근거를 붙여. 그래서 설득력이 무서운데, 좀 차갑게 느껴질 수 있어.",
    catchpoint: "화음(丁) + 금(酉) = 불이 금속을 다듬 → 디테일+분석이 '논리 정리형'으로 발현",
    bestMatch: "임진-m",
    worstMatch: "무오-f",
    rarity: 3,
  },

  // ── 55. 무자 (戊子) 남성 — 토(양) + 수 ──
  {
    id: "무자-m",
    ilju: "무자",
    hanja: "戊子",
    gender: "male",
    name: "참다참다 한방",
    emoji: "🌋",
    tagline: "365일 참다가 하루 터짐",
    stemElement: "토(土)",
    branchElement: "수(水)",
    yinyang: "양(陽)",
    tagColor: "bg-mustard",
    strengths: ["인내력", "뚝심", "폭발적 추진력"],
    weaknesses: ["속으로 담아두는 편", "생각 정리 후 말하는 편"],
    quote: "아 됐다. 이제부터 내 맘대로 함.",
    description: "단단한 땅 아래에 물이 흐르는 사주야. 여자 무자가 '겉은 차분 속은 야생'으로 선 넘으면 터진다면, 남자 무자는 아예 1년치를 모아서 한방에 터뜨리는 스타일이야. 평소엔 '괜찮아 괜찮아' 하다가 갑자기 사표 내거나 인생을 바꿔버리거든.",
    catchpoint: "토양(戊) + 수(子) = 땅 아래 물 → 물이 오래 갇히면 수압 폭발, 한방형",
    bestMatch: "을사-f",
    worstMatch: "병자-f",
    rarity: 3,
  },

  // ── 56. 경인 (庚寅) 여성 — 금(양) + 목 ──
  {
    id: "경인-f",
    ilju: "경인",
    hanja: "庚寅",
    gender: "female",
    name: "지면 잠 못잠",
    emoji: "🏆",
    tagline: "가위바위보도 지면 복기 들어감",
    stemElement: "금(金)",
    branchElement: "목(木)",
    yinyang: "양(陽)",
    tagColor: "bg-charcoal",
    strengths: ["경쟁심", "자기계발", "끈기"],
    weaknesses: ["목표 의식이 강함", "결과에 예민함"],
    quote: "아 진짜? 다음엔 절대 진다.",
    description: "날카로운 쇠가 나무를 만난 사주야. 남자 경인이 '승부욕 만렙'으로 1등을 향해 간다면, 여자 경인은 '지는 것 자체'가 싫은 타입이야. 보드게임에서도 지면 진짜 속상하거든. 그래서 뭐든 열심히 하는데 본인한테 좀 관대해져도 돼.",
    catchpoint: "금양(庚) + 목(寅) = 쇠가 나무를 깎음 → 깎는 힘이 '지기 싫음'으로 발현",
    bestMatch: "을묘-m",
    worstMatch: "갑인-m",
    rarity: 4,
  },

  // ── 57. 신축 (辛丑) 남성 — 금(음) + 토 ──
  {
    id: "신축-m",
    ilju: "신축",
    hanja: "辛丑",
    gender: "male",
    name: "확실한 길만 감",
    emoji: "⏳",
    tagline: "지름길보다 안전빵 선호",
    stemElement: "금(金)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-lavender",
    strengths: ["신중함", "완성도", "꾸준함"],
    weaknesses: ["느린 시작", "기회 놓침"],
    quote: "급하게 해서 좋을 거 하나도 없어.",
    description: "보석이 흙 속에 묻혀 있는 사주야. 여자 신축이 '슬로우 스타터'로 시간이 걸려도 결국 해낸다면, 남자 신축은 아예 빠른 길을 안 가. 확실한 길만 가거든. 남들이 '빨리 해!'라고 해도 본인 템포를 유지하는 게 강점인데, 가끔 타이밍을 놓칠 수 있어.",
    catchpoint: "금음(辛) + 토(丑) = 보석이 흙 속에 → 급하면 깨지니까 천천히 정확하게",
    bestMatch: "병오-f",
    worstMatch: "갑오-m",
    rarity: 2,
  },

  // ── 58. 임술 (壬戌) 여성 — 수(양) + 토 ──
  {
    id: "임술-f",
    ilju: "임술",
    hanja: "壬戌",
    gender: "female",
    name: "아이디어뱅크",
    emoji: "💡",
    tagline: "툭 던진 말이 회의 결론 됨",
    stemElement: "수(水)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-pink",
    strengths: ["창의력", "연결 사고", "직감"],
    weaknesses: ["산만함", "끝까지 밀어붙이기 약함"],
    quote: "아 잠깐! 갑자기 생각났는데 이거 진짜 되지 않아?",
    description: "물이 땅과 부딪히는 사주야. 남자 임술이 '한 끗 차이 천재'로 기발한데 갈팡질팡한다면, 여자 임술은 엉뚱한데 그게 되게 맞아. 회의 중에 갑자기 딴 소리 하는 것 같은데 '어? 그거 되는데?' 싶은 아이디어를 내는 타입이거든.",
    catchpoint: "수양(壬) + 토(戌) = 물이 땅과 부딪힘 → 충돌에서 나오는 번뜩임이 '적중'하는 방향",
    bestMatch: "정해-m",
    worstMatch: "기사-f",
    rarity: 5,
  },

  // ── 59. 갑술 (甲戌) 남성 — 목(양) + 토 ──
  {
    id: "갑술-m",
    ilju: "갑술",
    hanja: "甲戌",
    gender: "male",
    name: "우회로 개척자",
    emoji: "🦬",
    tagline: "조건이 안 맞으면 조건을 바꿔버림",
    stemElement: "목(木)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-neon-green",
    strengths: ["추진력", "돌파력", "자신감"],
    weaknesses: ["도전이 과할 때", "내 생각에 확신이 강함"],
    quote: "안 된다고? 그러면 방법을 바꾸면 되지.",
    description: "큰 나무가 마른 땅 위에 선 사주야. 여자 갑술이 '근거 없는 자신감'으로 믿음이 강하다면, 남자 갑술은 안 되는 걸 되게 만들어버리는 타입이야. 환경 탓 안 하고 환경을 바꾸거든. 진짜 무서운 추진력인데 가끔 무리수를 둘 때가 있어.",
    catchpoint: "목양(甲) + 토(戌) = 나무가 마른 땅에 → 안 되는 환경에서 오히려 뚫어버리는 힘",
    bestMatch: "계유-f",
    worstMatch: "경오-f",
    rarity: 4,
  },

  // ── 60. 계축 (癸丑) 여성 — 수(음) + 토 ──
  {
    id: "계축-f",
    ilju: "계축",
    hanja: "癸丑",
    gender: "female",
    name: "말수 적은 에이스",
    emoji: "🎻",
    tagline: "시키려고 보면 이미 해놨음",
    stemElement: "수(水)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-pink",
    strengths: ["실력", "자기관리", "묵묵한 성실"],
    weaknesses: ["조용한 존재감", "자기 표현이 조용한 편"],
    quote: "...(이미 끝나 있는 보고서를 올리며)",
    description: "작은 물이 단단한 땅 속으로 스며드는 사주야. 남자 계축이 '묵묵한 실력파'로 결과를 보여준다면, 여자 계축은 시키기도 전에 해놓는 타입이야. 팀에서 '이거 누가 했어?'하면 조용히 손 드는 그 사람이거든. 근데 너무 티를 안 내면 기여를 인정 못 받을 수 있어.",
    catchpoint: "수음(癸) + 토(丑) = 물이 땅속으로 스며듦 → 보이지 않게 일하는 선행형 실력파",
    bestMatch: "병자-m",
    worstMatch: "갑오-m",
    rarity: 2,
  },

  // ── 61. 을축 (乙丑) 남성 — 목(음) + 토 ──
  {
    id: "을축-m",
    ilju: "을축",
    hanja: "乙丑",
    gender: "male",
    name: "느긋한 야심가",
    emoji: "🌱",
    tagline: "급한 거 없는데 목표는 확실함",
    stemElement: "목(木)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-neon-green",
    strengths: ["끈기", "계획력", "현실감각"],
    weaknesses: ["속도 느림", "기회 놓침"],
    quote: "천천히 가도 돼. 어차피 내 자리야.",
    description: "작은 풀이 단단한 땅에 뿌리를 내리는 사주야. 목이 토를 극하니까 욕심은 있는데 표현이 안 드러나거든. '저 사람 욕심 없나?' 했는데 5년 후에 보면 원하는 자리에 가 있는 타입이야. 급하게 안 가도 돼, 근데 가끔은 기회 왔을 때 잡는 연습도 필요해.",
    catchpoint: "목음(乙) + 토(丑) = 풀이 단단한 땅을 극함 → 느긋해 보이지만 속에 야심",
    bestMatch: "경오-f",
    worstMatch: "신유-m",
    rarity: 2,
  },

  // ── 62. 을축 (乙丑) 여성 — 목(음) + 토 ──
  {
    id: "을축-f",
    ilju: "을축",
    hanja: "乙丑",
    gender: "female",
    name: "꾸준함이 무기",
    emoji: "🐌",
    tagline: "티 안 나게 계속 전진 중",
    stemElement: "목(木)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-neon-green",
    strengths: ["성실함", "자기관리", "책임감"],
    weaknesses: ["자기 표현이 조용한 편", "익숙한 방식 선호"],
    quote: "매일 조금씩. 그게 내 방식이야.",
    description: "풀이 무거운 흙을 뚫고 올라오는 사주야. 하루아침에 확 피는 타입은 아닌데, 매일 조금씩 꾸준히 하는 힘이 있거든. 1년 후에 뒤돌아보면 '와 이만큼 왔네' 하게 되는 타입이야. 근데 가끔 본인이 잘하고 있다는 걸 좀 인정해줘도 돼.",
    catchpoint: "목음(乙) + 토(丑) = 풀이 흙을 뚫음 → 매일 한 걸음, 누적의 힘",
    bestMatch: "경진-m",
    worstMatch: "갑오-f",
    rarity: 2,
  },

  // ── 63. 병인 (丙寅) 남성 — 화(양) + 목 ──
  {
    id: "병인-m",
    ilju: "병인",
    hanja: "丙寅",
    gender: "male",
    name: "불타는 돌격대장",
    emoji: "🐯",
    tagline: "생각하는 순간 하고 있음",
    stemElement: "화(火)",
    branchElement: "목(木)",
    yinyang: "양(陽)",
    tagColor: "bg-pop-orange",
    strengths: ["추진력", "자신감", "리더십"],
    weaknesses: ["계획 부족", "마무리 약함"],
    quote: "가면서 알아내면 돼.",
    description: "불이 나무를 만나서 더 세게 타는 사주야. 목생화(木生火)라서 에너지가 끊임없이 공급되거든. 뭔가 시작하면 속도가 장난 아닌데, 불이 너무 빨리 타면 연료가 떨어지는 것처럼 중간에 지칠 수 있어. 페이스 조절 좀 하면 진짜 무서운 사람이야.",
    catchpoint: "화양(丙) + 목(寅) = 불에 나무 공급 → 멈출 줄 모르는 추진력",
    bestMatch: "신축-f",
    worstMatch: "임자-m",
    rarity: 3,
  },

  // ── 64. 병인 (丙寅) 여성 — 화(양) + 목 ──
  {
    id: "병인-f",
    ilju: "병인",
    hanja: "丙寅",
    gender: "female",
    name: "텐션 최고봉",
    emoji: "🔥",
    tagline: "옆에 있으면 나까지 뭔가 하고 싶어짐",
    stemElement: "화(火)",
    branchElement: "목(木)",
    yinyang: "양(陽)",
    tagColor: "bg-pop-orange",
    strengths: ["열정 전파", "긍정", "행동력"],
    weaknesses: ["번아웃 위험", "텐션이 과할 때 있음"],
    quote: "같이 하자! 진짜 재밌을 거야!",
    description: "불이 나무 땔감을 만나서 활활 타는 사주야. 이 사람 옆에 있으면 나도 뭔가 해야 할 것 같은 에너지가 전파되거든. 모임의 분위기 메이커인데, 가끔 본인 에너지가 너무 세서 조용히 있고 싶은 사람을 압도할 수 있어. 쉬는 것도 생산적인 거야.",
    catchpoint: "화양(丙) + 목(寅) = 목생화, 에너지 무한 공급 → 열정이 주변까지 전파",
    bestMatch: "임술-m",
    worstMatch: "계축-m",
    rarity: 3,
  },

  // ── 65. 신미 (辛未) 남성 — 금(음) + 토 ──
  {
    id: "신미-m",
    ilju: "신미",
    hanja: "辛未",
    gender: "male",
    name: "인간 체크리스트",
    emoji: "🎯",
    tagline: "애매하면 시작 안 함",
    stemElement: "금(金)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-lavender",
    strengths: ["꼼꼼함", "완성도", "신중함"],
    weaknesses: ["시작 늦음", "완벽주의 과잉"],
    quote: "잠깐, 아직 준비 안 끝났어.",
    description: "보석이 따뜻한 흙에 감싸진 사주야. 토생금(土生金)이라 환경이 본인을 서포트해주거든. 근데 그게 너무 편하니까 '좀 더 다듬고 시작하자'가 끝이 없을 수 있어. 80%에서 출발해도 괜찮아, 나머지는 가면서 채워.",
    catchpoint: "금음(辛) + 토(未) = 흙이 금을 키움 → 준비가 완벽해야 움직이는 신중파",
    bestMatch: "병자-f",
    worstMatch: "갑자-m",
    rarity: 3,
  },

  // ── 66. 신미 (辛未) 여성 — 금(음) + 토 ──
  {
    id: "신미-f",
    ilju: "신미",
    hanja: "辛未",
    gender: "female",
    name: "예쁜 쓴소리 담당",
    emoji: "💅",
    tagline: "진심 담아서 쓴소리 해주는데 맞는 말만 함",
    stemElement: "금(金)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-lavender",
    strengths: ["조언력", "관찰력", "진심"],
    weaknesses: ["챙기려는 마음이 큼", "기대치 높음"],
    quote: "내가 이 말 안 하면 누가 해. 듣기 싫어도 들어.",
    description: "보석이 따뜻한 흙에 안겨 있는 사주야. 토생금이라 따뜻한 마음이 날카로움을 감싸주거든. 그래서 쓴소리를 해도 '아 맞는 말이긴 하네...'가 되는 타입이야. 근데 본인 기준으로 남을 재면 관계가 피곤해질 수 있어.",
    catchpoint: "금음(辛) + 토(未) = 따뜻한 흙이 보석을 키움 → 날카롭지만 진심이 담긴 조언",
    bestMatch: "병인-m",
    worstMatch: "을묘-f",
    rarity: 3,
  },

  // ── 67. 임신 (壬申) 남성 — 수(양) + 금 ──
  {
    id: "임신-m",
    ilju: "임신",
    hanja: "壬申",
    gender: "male",
    name: "효율 중독자",
    emoji: "⚙️",
    tagline: "비효율 절대 못 지나침",
    stemElement: "수(水)",
    branchElement: "금(金)",
    yinyang: "양(陽)",
    tagColor: "bg-pink",
    strengths: ["효율", "논리력", "시스템 사고"],
    weaknesses: ["감정보다 효율 우선", "쿨해 보임"],
    quote: "이거 왜 이렇게 하고 있어? 이렇게 하면 반으로 줄어드는데.",
    description: "큰 물이 금속 위를 흐르는 사주야. 금생수(金生水)라서 논리와 효율이 끝없이 공급되거든. 일할 때 진짜 유능한데, 사람 관계에서도 효율을 적용하면 '너 왜 이렇게 차가워?' 소리 들을 수 있어. 비효율도 감정의 일부라는 거, 가끔 떠올려봐.",
    catchpoint: "수양(壬) + 금(申) = 금생수, 논리 무한 공급 → 비효율을 못 참는 효율 마니아",
    bestMatch: "정해-f",
    worstMatch: "병오-m",
    rarity: 4,
  },

  // ── 68. 임신 (壬申) 여성 — 수(양) + 금 ──
  {
    id: "임신-f",
    ilju: "임신",
    hanja: "壬申",
    gender: "female",
    name: "쿨내 폭발",
    emoji: "🧊",
    tagline: "웬만한 일엔 표정도 안 바뀜",
    stemElement: "수(水)",
    branchElement: "금(金)",
    yinyang: "양(陽)",
    tagColor: "bg-pink",
    strengths: ["냉정함", "판단력", "독립심"],
    weaknesses: ["위로보다 해결책 제시", "독립적 판단"],
    quote: "울어서 해결되면 울지. 안 되니까 생각해.",
    description: "큰 물이 금속 위를 시원하게 흐르는 사주야. 금생수라서 머리가 항상 맑거든. 감정적인 상황에서도 '그래서 어떻게 할 건데?'가 먼저 나오는 타입이야. 근데 가끔 옆 사람은 그냥 들어주기만 해도 되는 거야. 해결책 말고 공감도 연습해봐.",
    catchpoint: "수양(壬) + 금(申) = 금생수, 맑은 물 → 감정 흔들림 없는 쿨한 판단력",
    bestMatch: "정묘-m",
    worstMatch: "병오-f",
    rarity: 4,
  },

  // ── 69. 정축 (丁丑) 남성 — 화(음) + 토 ──
  {
    id: "정축-m",
    ilju: "정축",
    hanja: "丁丑",
    gender: "male",
    name: "몰입 고수",
    emoji: "🕯️",
    tagline: "꽂히면 끝을 봄",
    stemElement: "화(火)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-pop-orange",
    strengths: ["집중력", "장인정신", "끈기"],
    weaknesses: ["관심 분야 집중형", "놓는 타이밍 못 잡음"],
    quote: "이거 아직 안 끝났어. 좀 더 할게.",
    description: "촛불이 흙 위에서 천천히 타는 사주야. 화생토(火生土)라서 에너지가 한 곳에 오래 모이거든. 관심 가는 분야가 생기면 미친 듯이 파고드는 타입이야. 근데 하나에 너무 꽂히면 다른 게 안 보이니까, 가끔 고개 들어서 주변도 봐.",
    catchpoint: "화음(丁) + 토(丑) = 촛불이 흙을 따뜻하게 함 → 한 곳에 오래 모이는 집중력",
    bestMatch: "임진-f",
    worstMatch: "계사-f",
    rarity: 3,
  },

  // ── 70. 정축 (丁丑) 여성 — 화(음) + 토 ──
  {
    id: "정축-f",
    ilju: "정축",
    hanja: "丁丑",
    gender: "female",
    name: "따뜻한 한마디 요정",
    emoji: "☕",
    tagline: "말 한마디로 사람 살림",
    stemElement: "화(火)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-pop-orange",
    strengths: ["위로", "공감력", "진정성"],
    weaknesses: ["본인 감정은 뒤로 미룸", "거절 못함"],
    quote: "힘들었지? 잘 버텼어, 진짜.",
    description: "작은 촛불이 차가운 흙을 데워주는 사주야. 화생토라서 에너지가 자연스럽게 주변을 따뜻하게 만들거든. 힘들 때 이 사람한테 전화하면 '아 나 괜찮구나' 싶어지는 마법이 있어. 근데 남 챙기느라 정작 본인이 힘들 때는 말을 못 해.",
    catchpoint: "화음(丁) + 토(丑) = 촛불이 흙을 데움 → 자연스럽게 주변을 따뜻하게",
    bestMatch: "임술-m",
    worstMatch: "신유-m",
    rarity: 2,
  },

  // ── 71. 무인 (戊寅) 남성 — 토(양) + 목 ──
  {
    id: "무인-m",
    ilju: "무인",
    hanja: "戊寅",
    gender: "male",
    name: "돌발 퀘스트 생성기",
    emoji: "🏔️",
    tagline: "갑자기 판 벌임",
    stemElement: "토(土)",
    branchElement: "목(木)",
    yinyang: "양(陽)",
    tagColor: "bg-mustard",
    strengths: ["포용력", "도전정신", "적응력"],
    weaknesses: ["방향 혼란", "예측 불가"],
    quote: "어? 나 갑자기 이거 해보고 싶은데?",
    description: "큰 산에 나무가 뚫고 올라오는 사주야. 목극토(木剋土)라서 안정적인 본인을 뒤흔드는 에너지가 내면에 있거든. 평소엔 듬직하고 안정적인데 갑자기 '나 이거 해볼래' 하고 새로운 걸 시작하는 타입이야. 그 반전이 매력이기도 해.",
    catchpoint: "토양(戊) + 목(寅) = 나무가 산을 뚫음 → 안정 속 돌발적 도전 욕구",
    bestMatch: "계사-f",
    worstMatch: "갑인-f",
    rarity: 3,
  },

  // ── 72. 무인 (戊寅) 여성 — 토(양) + 목 ──
  {
    id: "무인-f",
    ilju: "무인",
    hanja: "戊寅",
    gender: "female",
    name: "터프한 엄마곰",
    emoji: "🐻",
    tagline: "평소엔 곰인형, 내 사람 일엔 불곰",
    stemElement: "토(土)",
    branchElement: "목(木)",
    yinyang: "양(陽)",
    tagColor: "bg-mustard",
    strengths: ["보호 본능", "실행력", "의리"],
    weaknesses: ["과보호", "본인은 안 챙김"],
    quote: "누가 건들면 나한테 말해. 내가 가.",
    description: "큰 산에 호랑이가 깃든 사주야. 기본적으로 따뜻하고 포용력 있는데, 내 사람이 위험하면 바로 전투 모드 들어가거든. 주변에서 '이 사람 뒤에 있으면 안전하다'는 느낌을 받아. 근데 보호하느라 본인이 상처받는 건 좀 줄여봐.",
    catchpoint: "토양(戊) + 목(寅) = 산에 호랑이 → 따뜻하지만 내 편 지킬 땐 터프",
    bestMatch: "계유-m",
    worstMatch: "갑술-f",
    rarity: 3,
  },

  // ── 73. 기묘 (己卯) 남성 — 토(음) + 목 ──
  {
    id: "기묘-m",
    ilju: "기묘",
    hanja: "己卯",
    gender: "male",
    name: "부드러운 반항아",
    emoji: "🌾",
    tagline: "순해 보이는데 하기 싫은 건 절대 안함",
    stemElement: "토(土)",
    branchElement: "목(木)",
    yinyang: "음(陰)",
    tagColor: "bg-mustard",
    strengths: ["자기 주관", "유연함", "창의력"],
    weaknesses: ["돌려서 거부함", "표현 부족"],
    quote: "아 네~ (제 방식대로 할게여)",
    description: "부드러운 흙에 나무가 뿌리내린 사주야. 목극토인데 음기라서 갈등이 겉으로 안 터져. 대놓고 반항은 안 하는데 하기 싫으면 조용히 안 하거든. '네' 했는데 안 하고 있으면 이 유형일 확률 높아. 싫으면 싫다고 말하는 게 오히려 관계에 좋아.",
    catchpoint: "토음(己) + 목(卯) = 나무가 흙을 뚫지만 부드럽게 → 조용한 저항, 순한 반항",
    bestMatch: "갑오-f",
    worstMatch: "경진-m",
    rarity: 2,
  },

  // ── 74. 기묘 (己卯) 여성 — 토(음) + 목 ──
  {
    id: "기묘-f",
    ilju: "기묘",
    hanja: "己卯",
    gender: "female",
    name: "센스 수신율 200%",
    emoji: "🐰",
    tagline: "눈치가 남다름",
    stemElement: "토(土)",
    branchElement: "목(木)",
    yinyang: "음(陰)",
    tagColor: "bg-mustard",
    strengths: ["센스", "상황 파악", "배려"],
    weaknesses: ["눈치 과잉", "남을 먼저 챙기는 편"],
    quote: "아 그 상황에서 그건 좀... 내가 대신 할게.",
    description: "부드러운 흙에 토끼가 뛰노는 사주야. 내면의 갈등을 센스로 승화시킨 타입이거든. 모임에서 '이거 누가 하지?' 할 때 슬쩍 해결해놓는 사람이 이 유형이야. 근데 너무 눈치 보면서 맞추다 보면 정작 본인이 뭘 원하는지 모르게 될 수 있어.",
    catchpoint: "토음(己) + 목(卯) = 흙과 나무의 부드러운 긴장 → 갈등을 센스로 승화",
    bestMatch: "갑자-m",
    worstMatch: "경인-m",
    rarity: 2,
  },

  // ── 75. 신사 (辛巳) 남성 — 금(음) + 화 ──
  {
    id: "신사-m",
    ilju: "신사",
    hanja: "辛巳",
    gender: "male",
    name: "성장 중독자",
    emoji: "🔨",
    tagline: "비버임. 맨날 집 뿌수고 다시 만듬",
    stemElement: "금(金)",
    branchElement: "화(火)",
    yinyang: "음(陰)",
    tagColor: "bg-charcoal",
    strengths: ["자기 혁신", "집념", "성장욕"],
    weaknesses: ["무리하는 경향", "현재에 만족이 어려움"],
    quote: "이 정도론 부족해. 더 가야 해.",
    description: "보석이 불 속에서 달궈지는 사주야. 화극금(火剋金)이라 계속 자기를 녹여서 다시 만드는 에너지가 있거든. 작년의 나와 올해의 내가 다른 타입이야. 성장 속도가 빠른데, 스스로한테 너무 가혹하면 부서질 수 있어. 지금도 충분히 잘하고 있어.",
    catchpoint: "금음(辛) + 화(巳) = 불이 보석을 녹임 → 스스로를 깨부수며 성장",
    bestMatch: "임진-f",
    worstMatch: "을해-m",
    rarity: 4,
  },

  // ── 76. 신사 (辛巳) 여성 — 금(음) + 화 ──
  {
    id: "신사-f",
    ilju: "신사",
    hanja: "辛巳",
    gender: "female",
    name: "밖에선 ON 집에선 OFF",
    emoji: "🦋",
    tagline: "밖에선 인싸, 집에선 식물",
    stemElement: "금(金)",
    branchElement: "화(火)",
    yinyang: "음(陰)",
    tagColor: "bg-charcoal",
    strengths: ["표현력", "매력", "적응력"],
    weaknesses: ["혼자 있으면 심심함", "사람 만남에 지침"],
    quote: "사람 많은 데서 웃다가, 집 가면 폰도 안 봐.",
    description: "보석이 불꽃 속에 있는 사주야. 화극금이라 밖에서는 빛나는데 안에서는 계속 깎이는 느낌이 있거든. 사교적이고 매력적인데, 혼자 있을 때 갑자기 에너지가 방전되는 타입이야. 가끔은 꾸미지 않은 모습도 보여줘도 괜찮아.",
    catchpoint: "금음(辛) + 화(巳) = 불이 금을 깎음 → 밖에서 빛나는 만큼 안에서 소모",
    bestMatch: "임술-m",
    worstMatch: "병오-m",
    rarity: 4,
  },

  // ── 77. 계미 (癸未) 남성 — 수(음) + 토 ──
  {
    id: "계미-m",
    ilju: "계미",
    hanja: "癸未",
    gender: "male",
    name: "플랜B 장인",
    emoji: "🌧️",
    tagline: "일 생기기 전에 이미 대비 끝냄",
    stemElement: "수(水)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-pink",
    strengths: ["위기 대비", "세심함", "계획력"],
    weaknesses: ["신중한 편", "과잉 걱정"],
    quote: "근데 혹시 그거 안 되면 어떡해? ...미리 준비하자.",
    description: "작은 물이 흙에 막혀 있는 사주야. 토극수(土剋水)라서 항상 뭔가 막힌 느낌이 있거든. 그래서 '혹시 안 되면?'을 항상 생각하는 타입이야. 덕분에 위기 대비는 완벽한데, 너무 걱정만 하다 보면 정작 시작을 못 해. 일단 한 번 해보는 것도 답이야.",
    catchpoint: "수음(癸) + 토(未) = 흙이 물을 막음 → 항상 막힘을 예상, 걱정 프로",
    bestMatch: "병인-f",
    worstMatch: "무진-f",
    rarity: 2,
  },

  // ── 78. 계미 (癸未) 여성 — 수(음) + 토 ──
  {
    id: "계미-f",
    ilju: "계미",
    hanja: "癸未",
    gender: "female",
    name: "잔잔한 텐션 조절러",
    emoji: "🫧",
    tagline: "과열되면 슬쩍 온도 낮춰주고 감",
    stemElement: "수(水)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-pink",
    strengths: ["중재력", "차분함", "균형 감각"],
    weaknesses: ["조용한 존재감", "내 의견을 뒤로 미룸"],
    quote: "다들 잠깐, 한 번만 정리하고 가자.",
    description: "작은 물이 흙 사이로 스며드는 사주야. 토극수인데 음이라 부딪히지 않고 스며들거든. 회의가 과열되거나 분위기가 이상해질 때 한마디로 정리해주는 타입이야. 근데 항상 조율만 하다 보면 정작 본인 의견은 뒤로 밀릴 수 있어.",
    catchpoint: "수음(癸) + 토(未) = 물이 흙 사이로 스밈 → 부딪히지 않고 조율하는 힘",
    bestMatch: "병인-m",
    worstMatch: "무오-f",
    rarity: 2,
  },

  // ── 79. 갑신 (甲申) 남성 — 목(양) + 금 ──
  {
    id: "갑신-m",
    ilju: "갑신",
    hanja: "甲申",
    gender: "male",
    name: "성장통 체질",
    emoji: "🪓",
    tagline: "깎이면서 단단해짐",
    stemElement: "목(木)",
    branchElement: "금(金)",
    yinyang: "양(陽)",
    tagColor: "bg-neon-green",
    strengths: ["회복력", "역경에 강함", "성장력"],
    weaknesses: ["신중한 자기 점검", "상처 숨김"],
    quote: "아프긴 한데... 이러면서 크는 거지 뭐.",
    description: "큰 나무가 도끼를 만난 사주야. 금극목(金剋木)이라 계속 깎이는 느낌이 있거든. 근데 신기한 게 깎일수록 더 단단해지는 타입이야. 역경을 많이 겪은 만큼 내면이 강한데, 아픈 건 아프다고 말해도 돼. 혼자 다 버틸 필요 없어.",
    catchpoint: "목양(甲) + 금(申) = 도끼가 나무를 깎음 → 깎일수록 단단해지는 성장",
    bestMatch: "기사-f",
    worstMatch: "경인-m",
    rarity: 4,
  },

  // ── 80. 갑신 (甲申) 여성 — 목(양) + 금 ──
  {
    id: "갑신-f",
    ilju: "갑신",
    hanja: "甲申",
    gender: "female",
    name: "잔다르크 재림",
    emoji: "🪵",
    tagline: "멘탈이 방탄임. 못 뚫음",
    stemElement: "목(木)",
    branchElement: "금(金)",
    yinyang: "양(陽)",
    tagColor: "bg-neon-green",
    strengths: ["집념", "회복력", "도전정신"],
    weaknesses: ["고집", "공정함을 중시"],
    quote: "안 된다고? 그럼 다른 방법으로 다시.",
    description: "큰 나무가 쇠에 부딪히는 사주야. 금극목이라 앞에 벽이 항상 있거든. 근데 이 유형은 벽을 피하는 게 아니라 부딪혀서 뚫는 스타일이야. 거절을 밥 먹듯이 당해도 멘탈이 안 깨지는 게 진짜 무기야. 다만 가끔은 돌아가는 게 더 빠를 때도 있어.",
    catchpoint: "목양(甲) + 금(申) = 나무가 쇠에 부딪힘 → 거절에도 안 꺾이는 집념",
    bestMatch: "기미-m",
    worstMatch: "신유-m",
    rarity: 4,
  },

  // ── 81. 을유 (乙酉) 남성 — 목(음) + 금 ──
  {
    id: "을유-m",
    ilju: "을유",
    hanja: "乙酉",
    gender: "male",
    name: "섬세한 완벽주의자",
    emoji: "✂️",
    tagline: "1% 부족해도 다시 함",
    stemElement: "목(木)",
    branchElement: "금(金)",
    yinyang: "음(陰)",
    tagColor: "bg-neon-green",
    strengths: ["정교함", "미적 감각", "끈기"],
    weaknesses: ["본인에게 엄격함", "원칙을 중시함"],
    quote: "이거 아까 1% 부족했어. 다시 해야 돼.",
    description: "작은 풀이 날카로운 가위 옆에 있는 사주야. 금극목인데 음이라 깎이는 게 안으로 들어와. 스스로한테 엄격하고 퀄리티에 집착하거든. 결과물은 항상 좋은데 과정에서 본인이 너무 힘들어. '이 정도면 됐다'를 연습해봐.",
    catchpoint: "목음(乙) + 금(酉) = 풀이 가위를 만남 → 자기에게 가혹한 정교함",
    bestMatch: "병자-f",
    worstMatch: "신유-f",
    rarity: 3,
  },

  // ── 82. 을유 (乙酉) 여성 — 목(음) + 금 ──
  {
    id: "을유-f",
    ilju: "을유",
    hanja: "乙酉",
    gender: "female",
    name: "겉은 약해 속은 강철",
    emoji: "🌸",
    tagline: "꽃인 줄 알았는데 속은 철근임",
    stemElement: "목(木)",
    branchElement: "금(金)",
    yinyang: "음(陰)",
    tagColor: "bg-neon-green",
    strengths: ["내면의 강함", "독립심", "단호함"],
    weaknesses: ["경계심", "믿음 느림"],
    quote: "나 약해 보여? ...한번 해봐.",
    description: "작은 풀이 날카로운 금속 옆에서 자라는 사주야. 금극목이라 외부에서 압박이 오는데, 그걸 버텨낸 내면의 강도가 장난 아니거든. 처음에 부드러워 보여서 '만만하겠다' 했다가 단호한 모습에 놀라는 사람이 많아. 근데 가끔은 경계를 좀 내려놓아도 괜찮아.",
    catchpoint: "목음(乙) + 금(酉) = 풀이 금속 옆에서 자람 → 약해 보이지만 내면은 강철",
    bestMatch: "경진-m",
    worstMatch: "신해-m",
    rarity: 3,
  },

  // ── 83. 병술 (丙戌) 남성 — 화(양) + 토 ──
  {
    id: "병술-m",
    ilju: "병술",
    hanja: "丙戌",
    gender: "male",
    name: "뜨거운 의리파",
    emoji: "🐕",
    tagline: "한 번 마음 주면 오래 감",
    stemElement: "화(火)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-pop-orange",
    strengths: ["의리", "행동력", "솔직함"],
    weaknesses: ["호불호가 선명함", "순간 감정에 휘둘림"],
    quote: "내 편이면 뭐든 해줄 수 있어. 근데 배신은 안 돼.",
    description: "큰 불이 마른 땅 위에서 활활 타는 사주야. 화생토라서 에너지가 넘치고 주변을 따뜻하게 하는데, 그 에너지가 '내 사람'한테 집중되거든. 의리 하나로 살아가는 타입인데, 내 편 아닌 사람한테는 좀 차가울 수 있어. 세상에 편만 있는 건 아니야.",
    catchpoint: "화양(丙) + 토(戌) = 불이 땅을 달굼 → 뜨거운 에너지가 내 편한테 집중",
    bestMatch: "임진-f",
    worstMatch: "계축-m",
    rarity: 3,
  },

  // ── 84. 병술 (丙戌) 여성 — 화(양) + 토 ──
  {
    id: "병술-f",
    ilju: "병술",
    hanja: "丙戌",
    gender: "female",
    name: "텐션 DJ",
    emoji: "🎆",
    tagline: "모임 텐션을 200%로 올림",
    stemElement: "화(火)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-pop-orange",
    strengths: ["분위기 메이킹", "에너지", "리더십"],
    weaknesses: ["과한 텐션", "번아웃"],
    quote: "여기 왜 이렇게 조용해? 내가 왔다!!",
    description: "큰 불이 넓은 땅을 밝히는 사주야. 화생토라서 에너지가 안정적으로 퍼지거든. 모임에 이 사람이 오면 텐션이 확 올라가는 타입이야. 파티 플래너, 분위기 담당으로 무적인데, 가끔은 조용히 있고 싶을 때도 조용히 있어도 돼.",
    catchpoint: "화양(丙) + 토(戌) = 큰 불이 넓게 비춤 → 분위기를 확 살리는 에너지",
    bestMatch: "임술-m",
    worstMatch: "계유-m",
    rarity: 3,
  },

  // ── 85. 기축 (己丑) 남성 — 토(음) + 토 ──
  {
    id: "기축-m",
    ilju: "기축",
    hanja: "己丑",
    gender: "male",
    name: "느긋한 끝판왕",
    emoji: "🐄",
    tagline: "남들 뛰어도 자기 속도로 감",
    stemElement: "토(土)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-mustard",
    strengths: ["안정감", "인내", "실용주의"],
    weaknesses: ["느린 반응", "익숙한 방식 선호"],
    quote: "뭐가 급해? 천천히 하면 돼.",
    description: "부드러운 흙이 두 겹으로 쌓인 사주야. 토가 두 번이라 안정감이 극대화된 타입이거든. 주변이 아무리 소란스러워도 본인 페이스 잃지 않아. 그 차분함이 주변을 안심시키는데, 가끔 진짜 급한 건 좀 빨리 반응해줘야 해.",
    catchpoint: "토음(己) + 토(丑) = 흙 두 겹 → 세상 속도와 상관없이 내 페이스 유지",
    bestMatch: "갑오-f",
    worstMatch: "갑인-f",
    rarity: 2,
  },

  // ── 86. 기축 (己丑) 여성 — 토(음) + 토 ──
  {
    id: "기축-f",
    ilju: "기축",
    hanja: "己丑",
    gender: "female",
    name: "믿고 맡기는 사람",
    emoji: "🧱",
    tagline: "결국 다들 얘 찾게 됨",
    stemElement: "토(土)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-mustard",
    strengths: ["신뢰감", "책임감", "꾸준함"],
    weaknesses: ["거절이 어려움", "거절 어려움"],
    quote: "응, 맡겨. 내가 할게.",
    description: "부드러운 흙이 두 겹이라 무한 포용의 사주야. 주변에서 '이 사람한테 맡기면 된다'는 신뢰가 있거든. 그래서 이것저것 다 떠넘겨지는 경우도 있어. 책임감은 좋은데, 모든 걸 다 안아줄 필요는 없어. '안 돼'도 완전한 문장이야.",
    catchpoint: "토음(己) + 토(丑) = 흙이 두 겹으로 안정 → 사람들이 믿고 맡기는 신뢰감",
    bestMatch: "갑자-m",
    worstMatch: "갑인-m",
    rarity: 2,
  },

  // ── 87. 신묘 (辛卯) 남성 — 금(음) + 목 ──
  {
    id: "신묘-m",
    ilju: "신묘",
    hanja: "辛卯",
    gender: "male",
    name: "생각의 설계자",
    emoji: "🗡️",
    tagline: "말로는 못 이김",
    stemElement: "금(金)",
    branchElement: "목(木)",
    yinyang: "음(陰)",
    tagColor: "bg-charcoal",
    strengths: ["논리력", "언변", "분석력"],
    weaknesses: ["표현이 날카로움", "말 한마디에 관계가 흔들림"],
    quote: "아니 근데 그 논리가 맞아? 내가 설명해줄게.",
    description: "날카로운 보석이 나무를 깎는 사주야. 금극목이라 상대방의 논리를 해체하는 능력이 있거든. 토론이나 논쟁에서 거의 안 지는 타입인데, 이기는 게 항상 좋은 건 아니야. 가끔은 상대 말도 한번 들어보고, '그래 네 말도 맞네'도 해봐.",
    catchpoint: "금음(辛) + 목(卯) = 보석이 나무를 깎음 → 논리로 상대를 해체",
    bestMatch: "병인-f",
    worstMatch: "을묘-f",
    rarity: 3,
  },

  // ── 88. 신묘 (辛卯) 여성 — 금(음) + 목 ──
  {
    id: "신묘-f",
    ilju: "신묘",
    hanja: "辛卯",
    gender: "female",
    name: "인간 정리정돈",
    emoji: "📐",
    tagline: "복잡할수록 더 차분해짐",
    stemElement: "금(金)",
    branchElement: "목(木)",
    yinyang: "음(陰)",
    tagColor: "bg-charcoal",
    strengths: ["정리력", "구조화", "판단력"],
    weaknesses: ["융통성 부족", "기준이 분명함"],
    quote: "이거 정리 안 하면 나 불편해서 못 살아.",
    description: "날카로운 보석이 나뭇가지를 다듬는 사주야. 금극목이라 복잡한 걸 깔끔하게 정리하는 힘이 있거든. 서류든 인간관계든 꼬인 거 풀어주는 능력이 있어. 근데 모든 걸 깔끔하게 맞출 수는 없다는 것도 받아들이면 좀 편해질 거야.",
    catchpoint: "금음(辛) + 목(卯) = 금이 나무를 다듬 → 복잡한 걸 깔끔하게 정리",
    bestMatch: "병술-m",
    worstMatch: "을해-m",
    rarity: 3,
  },

  // ── 89. 임인 (壬寅) 남성 — 수(양) + 목 ──
  {
    id: "임인-m",
    ilju: "임인",
    hanja: "壬寅",
    gender: "male",
    name: "가능성 수집가",
    emoji: "🌊",
    tagline: "안 해본 거 = 버킷리스트",
    stemElement: "수(水)",
    branchElement: "목(木)",
    yinyang: "양(陽)",
    tagColor: "bg-pink",
    strengths: ["호기심", "적응력", "성장력"],
    weaknesses: ["산만", "하나에 집중 어려움"],
    quote: "이것도 해보고 싶고 저것도 해보고 싶은데... 인생이 짧아.",
    description: "큰 물이 나무에 영양을 공급하는 사주야. 수생목(水生木)이라 에너지가 성장으로 바로 연결되거든. 새로운 거 배우는 속도가 빠르고 가능성을 보는 눈이 있어. 근데 이것저것 다 하다 보면 하나도 깊이 못 갈 수 있어. 가끔은 하나 파는 것도 전략이야.",
    catchpoint: "수양(壬) + 목(寅) = 수생목, 물이 나무를 키움 → 끝없는 성장 욕구와 호기심",
    bestMatch: "정해-f",
    worstMatch: "경인-m",
    rarity: 3,
  },

  // ── 90. 임인 (壬寅) 여성 — 수(양) + 목 ──
  {
    id: "임인-f",
    ilju: "임인",
    hanja: "壬寅",
    gender: "female",
    name: "직감이 레이더",
    emoji: "🐅",
    tagline: "육감으로 다 맞힘",
    stemElement: "수(水)",
    branchElement: "목(木)",
    yinyang: "양(陽)",
    tagColor: "bg-pink",
    strengths: ["직관", "결단력", "순발력"],
    weaknesses: ["감각 우선", "관심사가 자주 바뀜"],
    quote: "왜인지 모르겠는데 이쪽이야. 가자.",
    description: "큰 물이 호랑이를 만난 사주야. 수생목이라 에너지가 행동으로 바로 연결되거든. '왜?'라고 물으면 설명 못 하는데 결과적으로 맞는 경우가 많아. 직감이 좋은 건 축복인데, 가끔은 '왜 이렇게 생각했지?'를 정리해보면 더 강해져.",
    catchpoint: "수양(壬) + 목(寅) = 수생목, 물이 호랑이를 키움 → 직감이 행동으로 바로 연결",
    bestMatch: "정축-m",
    worstMatch: "경오-f",
    rarity: 3,
  },

  // ── 91. 계묘 (癸卯) 남성 — 수(음) + 목 ──
  {
    id: "계묘-m",
    ilju: "계묘",
    hanja: "癸卯",
    gender: "male",
    name: "촉 레이더",
    emoji: "🎯",
    tagline: "논리 없이 감으로 맞추는데 그게 다 맞음",
    stemElement: "수(水)",
    branchElement: "목(木)",
    yinyang: "음(陰)",
    tagColor: "bg-pink",
    strengths: ["직관력", "창의성", "유연함"],
    weaknesses: ["감각 우선", "일관성 부족"],
    quote: "왜냐면... 그냥 느낌이 그래.",
    description: "이슬비가 풀잎을 키우는 사주야. 수생목이라 에너지가 자연스럽게 흐르거든. 데이터나 근거 없이도 정답을 찍어내는 타입이야. '어떻게 알았어?'라고 물어보면 '그냥'이라고 대답하는데 진짜 맞아. 근데 가끔 본인도 왜 맞는지 설명을 못 해서 답답할 때가 있어.",
    catchpoint: "수음(癸) + 목(卯) = 이슬비가 풀을 키움 → 조용히 스며드는 직관력",
    bestMatch: "병오-f",
    worstMatch: "경인-m",
    rarity: 3,
  },

  // ── 92. 계묘 (癸卯) 여성 — 수(음) + 목 ──
  {
    id: "계묘-f",
    ilju: "계묘",
    hanja: "癸卯",
    gender: "female",
    name: "말랑말랑 독종",
    emoji: "🐰",
    tagline: "착한 얼굴에 그렇지 못한 태도",
    stemElement: "수(水)",
    branchElement: "목(木)",
    yinyang: "음(陰)",
    tagColor: "bg-pink",
    strengths: ["적응력", "끈기", "소프트파워"],
    weaknesses: ["돌려서 표현함", "속마음 안 보여줌"],
    quote: "괜찮아~ (근데 절대 안 괜찮음)",
    description: "이슬비가 토끼풀을 키우는 사주야. 수생목으로 에너지가 부드럽게 흐르는데, 겉은 말랑하지만 한번 마음먹으면 끝까지 가거든. 주변에서 '저 사람 순한 줄 알았는데?' 하는 경우가 많아. 부드러운 게 약한 게 아니라는 걸 증명하는 타입이야.",
    catchpoint: "수음(癸) + 목(卯) = 이슬비+토끼 → 부드러워 보이지만 절대 포기 안 함",
    bestMatch: "병오-m",
    worstMatch: "경인-m",
    rarity: 3,
  },

  // ── 93. 갑진 (甲辰) 남성 — 목(양) + 토 ──
  {
    id: "갑진-m",
    ilju: "갑진",
    hanja: "甲辰",
    gender: "male",
    name: "빅픽처 설계자",
    emoji: "🏗️",
    tagline: "지금 이거 왜 하냐고? 3년 뒤에 알게 됨",
    stemElement: "목(木)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-neon-green",
    strengths: ["장기 비전", "실행력", "배포"],
    weaknesses: ["생각 정리 후 말하는 편", "독립적 판단"],
    quote: "지금은 이해 못 해도 돼. 나중에 알게 될 거야.",
    description: "큰 나무가 용의 땅 위에 서 있는 사주야. 목극토인데 양기가 강해서 오히려 뚫고 나가는 힘이 있거든. 스케일이 크고 멀리 보는 타입이야. '이 사람 뭐 하는 거지?' 했는데 나중에 보면 다 연결되어 있어. 근데 혼자만 큰 그림 보면서 설명을 안 해주면 외로워질 수 있어.",
    catchpoint: "목양(甲) + 토(辰) = 큰 나무가 용의 땅에 뿌리 → 장기적 스케일, 큰 그림을 그리는 힘",
    bestMatch: "기유-f",
    worstMatch: "경술-m",
    rarity: 4,
  },

  // ── 94. 갑진 (甲辰) 여성 — 목(양) + 토 ──
  {
    id: "갑진-f",
    ilju: "갑진",
    hanja: "甲辰",
    gender: "female",
    name: "끝을 보는 체질",
    emoji: "🌱",
    tagline: "안 되면 방법을 바꾸지, 목표를 안 바꿈",
    stemElement: "목(木)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-neon-green",
    strengths: ["목표 의식", "인내", "현실 감각"],
    weaknesses: ["소신이 뚜렷함", "쉬는 걸 못함"],
    quote: "아직 안 됐으면 덜 한 거야.",
    description: "큰 나무가 단단한 땅을 뚫고 자라는 사주야. 목극토라 저항이 있는데 그걸 뚫어내는 힘이 있거든. 남들이 포기할 타이밍에 '한 번만 더'를 외치는 타입이야. 근데 가끔은 안 되는 걸 인정하는 것도 용기라는 거 기억해.",
    catchpoint: "목양(甲) + 토(辰) = 나무가 땅을 뚫음 → 저항을 뚫는 집요한 성장력",
    bestMatch: "기유-m",
    worstMatch: "경술-f",
    rarity: 4,
  },

  // ── 95. 정미 (丁未) 남성 — 화(음) + 토 ──
  {
    id: "정미-m",
    ilju: "정미",
    hanja: "丁未",
    gender: "male",
    name: "따뜻한 잔소리꾼",
    emoji: "☕",
    tagline: "잔소리인데 기분이 안 나쁨",
    stemElement: "화(火)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-pop-orange",
    strengths: ["배려", "관찰력", "꼼꼼함"],
    weaknesses: ["챙기려는 마음이 큼", "걱정 많음"],
    quote: "그거 그렇게 하면 안 돼... 아 내가 할게.",
    description: "작은 불꽃이 따뜻한 흙을 데우는 사주야. 화생토라 에너지가 자연스럽게 흘러. 주변 사람한테 이것저것 챙겨주는 타입인데, 잔소리가 진짜 따뜻해서 '또 시작이다' 하면서도 결국 웃게 돼.",
    catchpoint: "화음(丁) + 토(未) = 작은 불이 흙을 따뜻하게 함 → 따뜻한 에너지가 자연스럽게 흘러넘침",
    bestMatch: "임자-f",
    worstMatch: "계묘-m",
    rarity: 2,
  },

  // ── 96. 정미 (丁未) 여성 — 화(음) + 토 ──
  {
    id: "정미-f",
    ilju: "정미",
    hanja: "丁未",
    gender: "female",
    name: "감정 레이더",
    emoji: "🫖",
    tagline: "말 꺼내기 전에 이미 눈치챔",
    stemElement: "화(火)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-pop-orange",
    strengths: ["공감력", "직관", "정서적 안정"],
    weaknesses: ["감정 과몰입", "본인 감정 후순위"],
    quote: "오늘 무슨 일 있었지? 표정이 다르던데.",
    description: "작은 촛불이 포근한 땅을 비추는 사주야. 화생토로 에너지가 안정적으로 흘러서 주변 사람 감정을 너무 잘 읽어. 가끔 '투시 능력 있냐'는 소리도 듣거든. 상담사 체질인데, 남의 감정만 처리하다 본인 감정은 방치할 때가 있어.",
    catchpoint: "화음(丁) + 토(未) = 촛불이 땅을 비춤 → 작은 빛으로 감정의 결까지 읽어냄",
    bestMatch: "임자-m",
    worstMatch: "계묘-f",
    rarity: 2,
  },

  // ── 97. 무신 (戊申) 남성 — 토(양) + 금 ──
  {
    id: "무신-m",
    ilju: "무신",
    hanja: "戊申",
    gender: "male",
    name: "결과물 뽑는 기계",
    emoji: "⚙️",
    tagline: "쓸데없는 과정 빼고 결과만 딱 냄",
    stemElement: "토(土)",
    branchElement: "금(金)",
    yinyang: "양(陽)",
    tagColor: "bg-mustard",
    strengths: ["효율", "체계화", "실용적 사고"],
    weaknesses: ["융통성 부족", "감정보다 효율 우선"],
    quote: "그거 왜 두 번 해? 한 번에 끝내.",
    description: "큰 산에서 쇠가 나오는 사주야. 토생금이라 결과물을 뽑아내는 힘이 좋거든. 모든 일에서 '이게 제일 빠른 길이 뭐지?'를 먼저 생각하는 타입이야. 근데 효율만 따지다 보면 사람 마음을 놓칠 때가 있어.",
    catchpoint: "토양(戊) + 금(申) = 산에서 금을 캐냄 → 최단 경로로 결과를 뽑아내는 힘",
    bestMatch: "계묘-f",
    worstMatch: "병오-m",
    rarity: 3,
  },

  // ── 98. 무신 (戊申) 여성 — 토(양) + 금 ──
  {
    id: "무신-f",
    ilju: "무신",
    hanja: "戊申",
    gender: "female",
    name: "정리의 신",
    emoji: "📋",
    tagline: "난장판에서도 정리할 건 찾음",
    stemElement: "토(土)",
    branchElement: "금(金)",
    yinyang: "양(陽)",
    tagColor: "bg-mustard",
    strengths: ["조직력", "판단력", "위기 대처"],
    weaknesses: ["직접 챙기고 싶어함", "기대치가 높은 편"],
    quote: "잠깐, 이거 정리부터 하고 시작하자.",
    description: "큰 산이 보석을 품고 있는 사주야. 토생금이라 어지러운 상황에서 핵심을 딱 잡아내고 정리하는 능력이 있거든. 프로젝트 하면 이 사람한테 일단 맡기면 구조가 생겨. 근데 남한테도 본인 기준을 적용하면 충돌이 날 수 있어.",
    catchpoint: "토양(戊) + 금(申) = 산이 보석을 품음 → 혼돈에서 핵심을 추출하는 정리력",
    bestMatch: "계묘-m",
    worstMatch: "병오-f",
    rarity: 3,
  },

  // ── 99. 기유 (己酉) 남성 — 토(음) + 금 ──
  {
    id: "기유-m",
    ilju: "기유",
    hanja: "己酉",
    gender: "male",
    name: "한 우물 장인",
    emoji: "🎻",
    tagline: "하나만 파는데 그 하나가 미쳤음",
    stemElement: "토(土)",
    branchElement: "금(金)",
    yinyang: "음(陰)",
    tagColor: "bg-mustard",
    strengths: ["전문성", "집중력", "장인정신"],
    weaknesses: ["관심 분야 집중형", "익숙한 방식 선호"],
    quote: "이거 하나는 누구한테도 안 져.",
    description: "부드러운 흙이 정교한 보석을 품고 있는 사주야. 토생금이라 한 곳에 에너지를 모아서 뽑아내는 힘이 강해. 한 분야를 깊게 파고드는 장인 타입이거든. 넓게 아는 건 관심 없고, 한 우물에서 끝을 보려고 해. 대신 그 우물 밖 세상도 있다는 걸 가끔 떠올려봐.",
    catchpoint: "토음(己) + 금(酉) = 흙이 보석을 감쌈 → 한 분야에 몰입하는 장인 기질",
    bestMatch: "갑진-f",
    worstMatch: "병자-f",
    rarity: 3,
  },

  // ── 100. 기유 (己酉) 여성 — 토(음) + 금 ──
  {
    id: "기유-f",
    ilju: "기유",
    hanja: "己酉",
    gender: "female",
    name: "취향 직진러",
    emoji: "✨",
    tagline: "기면 기고 아니면 아님",
    stemElement: "토(土)",
    branchElement: "금(金)",
    yinyang: "음(陰)",
    tagColor: "bg-lavender",
    strengths: ["심미안", "일관성", "자기 확신"],
    weaknesses: ["기준이 높은 편", "취향이 확고함"],
    quote: "나는 이게 좋아. 이유? 좋으니까.",
    description: "흙 속에서 다듬어진 보석 같은 사주야. 토생금으로 본인만의 심미안이 단단하게 형성돼 있어. 취향이 확고하고 절대 흔들리지 않거든. '요즘 뭐가 유행이래?'에 관심 없고 본인이 좋은 게 최고야. 대신 남의 취향도 존중해 주는 여유가 있으면 더 좋아.",
    catchpoint: "토음(己) + 금(酉) = 흙이 보석을 다듬음 → 자기만의 심미안이 확고",
    bestMatch: "갑진-m",
    worstMatch: "병자-m",
    rarity: 3,
  },

  // ── 101. 경술 (庚戌) 남성 — 금(양) + 토 ──
  {
    id: "경술-m",
    ilju: "경술",
    hanja: "庚戌",
    gender: "male",
    name: "의리 끝판왕",
    emoji: "🐕",
    tagline: "내 편은 끝까지, 배신 죽어도 안함",
    stemElement: "금(金)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-charcoal",
    strengths: ["의리", "책임감", "보호본능"],
    weaknesses: ["이분법적 판단", "신뢰가 깨지면 회복 어려움"],
    quote: "내 사람한테 손대지 마.",
    description: "단단한 쇠가 마른 땅 위에 선 사주야. 토생금이라 땅이 쇠를 더 단단하게 만들어주거든. 내 편이라고 인정한 사람한테는 진짜 끝까지 가. 대신 한번 배신당했다고 느끼면 돌아서는 것도 칼 같아. 세상이 꼭 흑백만은 아니라는 것도 알아두면 좋아.",
    catchpoint: "금양(庚) + 토(戌) = 쇠가 개의 땅 위에 → 충견 같은 의리, 배신 용납 불가",
    bestMatch: "을미-f",
    worstMatch: "갑진-m",
    rarity: 3,
  },

  // ── 102. 경술 (庚戌) 여성 — 금(양) + 토 ──
  {
    id: "경술-f",
    ilju: "경술",
    hanja: "庚戌",
    gender: "female",
    name: "거짓말 탐지기",
    emoji: "🔔",
    tagline: "거짓말하면 눈빛부터 달라짐",
    stemElement: "금(金)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-charcoal",
    strengths: ["통찰력", "정직", "판단력"],
    weaknesses: ["의심 과다", "마음 여는 데 시간 걸림"],
    quote: "방금 그거 진심 아니지?",
    description: "강철이 두꺼운 땅 위에 있는 사주야. 토생금이라 직감의 날이 더 예리해지거든. 사람을 읽는 눈이 날카로워서 거짓말이나 가식을 바로 캐치해. 덕분에 진짜 사람을 곁에 두는데, 너무 의심하면 진심인 사람도 멀어질 수 있어.",
    catchpoint: "금양(庚) + 토(戌) = 쇠의 날카로움+땅의 직감 → 가식을 꿰뚫어 봄",
    bestMatch: "을미-m",
    worstMatch: "갑진-f",
    rarity: 3,
  },

  // ── 103. 임자 (壬子) 남성 — 수(양) + 수 ──
  {
    id: "임자-m",
    ilju: "임자",
    hanja: "壬子",
    gender: "male",
    name: "멈추면 죽는 상어",
    emoji: "🦈",
    tagline: "복작복작사부작사부작함",
    stemElement: "수(水)",
    branchElement: "수(水)",
    yinyang: "양(陽)",
    tagColor: "bg-pink",
    strengths: ["행동력", "적응력", "아이디어"],
    weaknesses: ["안정 못함", "멈추면 아쉬운 타입"],
    quote: "쉬는 날인데... 뭐라도 해야 할 것 같아.",
    description: "큰 물이 또 물을 만나는 사주야. 수(水)가 두 겹이라 에너지가 흘러야 직성이 풀리거든. 가만히 있으면 불안하고, 항상 뭔가를 하고 있어야 해. 이 사람한테 '아무것도 안 하는 날'은 고문이야. 근데 가끔은 멈추는 것도 전략이라는 거 기억해.",
    catchpoint: "수양(壬) + 수(子) = 큰 물이 또 물 → 멈춤이 없는 끊임없는 흐름",
    bestMatch: "정해-f",
    worstMatch: "무진-f",
    rarity: 4,
  },

  // ── 104. 임자 (壬子) 여성 — 수(양) + 수 ──
  {
    id: "임자-f",
    ilju: "임자",
    hanja: "壬子",
    gender: "female",
    name: "무드 메이커",
    emoji: "🌊",
    tagline: "이 사람 기분에 따라 단톡방 분위기가 바뀜",
    stemElement: "수(水)",
    branchElement: "수(水)",
    yinyang: "양(陽)",
    tagColor: "bg-pink",
    strengths: ["영향력", "감수성", "표현력"],
    weaknesses: ["감수성이 풍부함", "영향력이 과함"],
    quote: "나 기분 좋으면 다 좋은 거 아니야?",
    description: "큰 물결이 또 물결을 만나는 사주야. 수 두 겹이라 감정의 파도가 크고 주변에 영향을 미치거든. 이 사람이 웃으면 모임이 밝아지고, 우울하면 다 같이 가라앉는 타입이야. 그 영향력을 알고 잘 쓰면 진짜 대단한 사람이 돼.",
    catchpoint: "수양(壬) + 수(子) = 물결이 물결을 만남 → 감정 파도가 주변을 다 움직임",
    bestMatch: "병오-m",
    worstMatch: "무진-m",
    rarity: 4,
  },

  // ── 105. 을미 (乙未) 남성 — 목(음) + 토 ──
  {
    id: "을미-m",
    ilju: "을미",
    hanja: "乙未",
    gender: "male",
    name: "환생한 간디",
    emoji: "🌾",
    tagline: "싸우느니 참고, 참느니 웃음",
    stemElement: "목(木)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-neon-green",
    strengths: ["온화함", "중재력", "인내"],
    weaknesses: ["갈등 회피", "본심 숨김"],
    quote: "그래그래~ 네 말이 맞아~ (속: 아닌데)",
    description: "작은 풀이 따뜻한 땅에서 자라는 사주야. 목극토인데 부드럽게 풀어가려는 성향이 있어. 갈등이 생기면 본인이 양보하는 편이거든. 근데 너무 참다 보면 나중에 한꺼번에 터질 수 있으니 작을 때 표현하는 연습이 필요해.",
    catchpoint: "목음(乙) + 토(未) = 풀이 땅과 공존 → 상극을 부드럽게 넘기는 온화함",
    bestMatch: "경술-f",
    worstMatch: "신유-m",
    rarity: 2,
  },

  // ── 106. 을미 (乙未) 여성 — 목(음) + 토 ──
  {
    id: "을미-f",
    ilju: "을미",
    hanja: "乙未",
    gender: "female",
    name: "인맥 자석",
    emoji: "🧲",
    tagline: "뭐 안 했는데 사람이 모임",
    stemElement: "목(木)",
    branchElement: "토(土)",
    yinyang: "음(陰)",
    tagColor: "bg-neon-green",
    strengths: ["친화력", "포용", "편안한 에너지"],
    weaknesses: ["거절 못함", "본인 우선순위 밀림"],
    quote: "아 진짜? 와~ 좋다! (진심 리액션)",
    description: "풀이 따뜻한 들판에서 피어나는 사주야. 목극토이지만 음이라 대립하지 않고 어우러지거든. 특별히 뭘 하는 게 아닌데 사람들이 모여들어. 편하고 따뜻한 에너지가 있어서 '쟤 옆에 있으면 좋아'라는 소리를 많이 들어. 대신 거절을 못 해서 본인이 지칠 때가 있어.",
    catchpoint: "목음(乙) + 토(未) = 풀이 들판에 핌 → 자연스럽게 사람이 모이는 에너지",
    bestMatch: "경술-m",
    worstMatch: "신유-f",
    rarity: 2,
  },

  // ── 107. 무술 (戊戌) 남성 — 토(양) + 토 ──
  {
    id: "무술-m",
    ilju: "무술",
    hanja: "戊戌",
    gender: "male",
    name: "안정감 풀옵션",
    emoji: "🧱",
    tagline: "유행 안 타고, 사람도 안 바꿈",
    stemElement: "토(土)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-mustard",
    strengths: ["한결같음", "포용력", "묵묵한 지지"],
    weaknesses: ["익숙한 방식 선호", "새 시도에 시간 걸림"],
    quote: "나는 그냥 늘 이 자리에 있을게.",
    description: "넓은 땅이 또 땅을 만난 사주야. 유행에 흔들리지 않고, 사람도 쉽게 바꾸지 않거든. 오래 알수록 편해지는 타입이야. '이 사람은 변하지 않는다'는 게 주변한테는 오히려 큰 안심이 되거든.",
    catchpoint: "토양(戊) + 토(戌) = 넓은 땅 두 겹 → 한결같아서 오히려 신뢰가 되는 타입",
    bestMatch: "갑자-f",
    worstMatch: "갑인-f",
    rarity: 3,
  },

  // ── 108. 무술 (戊戌) 여성 — 토(양) + 토 ──
  {
    id: "무술-f",
    ilju: "무술",
    hanja: "戊戌",
    gender: "female",
    name: "엄마가 셋인 느낌",
    emoji: "🫂",
    tagline: "자꾸 챙기다 보니 내가 엄마됨",
    stemElement: "토(土)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-mustard",
    strengths: ["포용력", "책임감", "돌봄"],
    weaknesses: ["과보호", "번아웃"],
    quote: "밥은? 잤어? 감기약 먹었어?",
    description: "넓은 대지가 또 대지와 만난 사주야. 포용력이 두 배라 주변 사람을 진짜 가족처럼 챙기거든. '엄마 아니고 친구야' 해도 본능적으로 챙기게 되는 타입이야. 근데 본인도 누군가한테 챙김 받아야 하는 거 잊지 마.",
    catchpoint: "토양(戊) + 토(戌) = 대지 두 겹 → 포용이 두 배, 본능적 돌봄 체질",
    bestMatch: "갑자-m",
    worstMatch: "갑인-m",
    rarity: 2,
  },

  // ── 109. 기해 (己亥) 남성 — 토(음) + 수 ──
  {
    id: "기해-m",
    ilju: "기해",
    hanja: "己亥",
    gender: "male",
    name: "겉바속촉 대표",
    emoji: "🥐",
    tagline: "인간 츤데레",
    stemElement: "토(土)",
    branchElement: "수(水)",
    yinyang: "음(陰)",
    tagColor: "bg-mustard",
    strengths: ["속깊음", "실용적 배려", "침착"],
    weaknesses: ["표현 서투름", "오해 받기 쉬움"],
    quote: "아 그거? 그냥 지나가다 생각나서. (계획적임)",
    description: "흙이 깊은 물을 담고 있는 사주야. 토극수라 겉과 속의 온도차가 있거든. 말은 무뚝뚝한데 행동으로는 다 챙기는 타입이야. '이 사람 나한테 관심 없나?' 했는데 알고 보면 제일 신경 쓰고 있었던 거야.",
    catchpoint: "토음(己) + 수(亥) = 흙이 물을 품음 → 겉은 무심한데 속은 따뜻한 갭",
    bestMatch: "갑오-f",
    worstMatch: "병오-m",
    rarity: 3,
  },

  // ── 110. 기해 (己亥) 여성 — 토(음) + 수 ──
  {
    id: "기해-f",
    ilju: "기해",
    hanja: "己亥",
    gender: "female",
    name: "흔들림 없는 마이웨이",
    emoji: "🐷",
    tagline: "세상이 난리여도 안 흔들림",
    stemElement: "토(土)",
    branchElement: "수(水)",
    yinyang: "음(陰)",
    tagColor: "bg-mustard",
    strengths: ["평정심", "자기 페이스", "스트레스 관리"],
    weaknesses: ["긴급 상황 대처 느림", "무관심으로 오해"],
    quote: "급해? 급하다고 빨리 되는 거 아닌데.",
    description: "부드러운 흙이 깊은 물 위에 있는 사주야. 토극수인데 음이라 다투지 않고 제어하는 느낌이거든. 주변이 아무리 급해도 본인 페이스를 잘 지켜. 처음엔 '저 사람 왜 저래?' 하는데 나중에 보면 이 사람이 제일 멀쩡해.",
    catchpoint: "토음(己) + 수(亥) = 흙이 물 위에 → 어떤 파도에도 흔들리지 않는 평정심",
    bestMatch: "갑오-m",
    worstMatch: "병오-f",
    rarity: 2,
  },

  // ── 111. 경자 (庚子) 남성 — 금(양) + 수 ──
  {
    id: "경자-m",
    ilju: "경자",
    hanja: "庚子",
    gender: "male",
    name: "논리 정수기",
    emoji: "🧊",
    tagline: "복잡할수록 또렷해짐",
    stemElement: "금(金)",
    branchElement: "수(水)",
    yinyang: "양(陽)",
    tagColor: "bg-charcoal",
    strengths: ["논리력", "객관성", "문제 해결"],
    weaknesses: ["위로보다 해결책 제시", "말이 너무 직설적"],
    quote: "그건 너 잘못이긴 해.",
    description: "칼날이 차가운 물을 만나는 사주야. 금생수라 머리가 잘 돌아가고 논리가 탄탄해. 근데 사실만 말하다 보면 상대방이 상처받는 걸 못 느끼는 경우가 있어. 맞는 말이어도 타이밍과 표현이 있다는 거 기억해.",
    catchpoint: "금양(庚) + 수(子) = 쇠가 물을 만남 → 날카로운 논리+차가운 팩트 조합",
    bestMatch: "을미-f",
    worstMatch: "병오-f",
    rarity: 4,
  },

  // ── 112. 경자 (庚子) 여성 — 금(양) + 수 ──
  {
    id: "경자-f",
    ilju: "경자",
    hanja: "庚子",
    gender: "female",
    name: "뒤끝 저장 안 함",
    emoji: "❄️",
    tagline: "끝났다 싶으면 뒤도 안 봄",
    stemElement: "금(金)",
    branchElement: "수(水)",
    yinyang: "양(陽)",
    tagColor: "bg-lavender",
    strengths: ["결단력", "독립심", "냉정한 판단"],
    weaknesses: ["쿨해 보임", "정리가 빠른 편"],
    quote: "끝나면 끝난 거야. 미련 같은 거 없어.",
    description: "강철이 차가운 물과 함께 있는 사주야. 금생수라 에너지가 시원하게 흘러가거든. 감정에 휘둘리지 않고 깔끔하게 정리하는 능력이 있어. 연애든 우정이든 '아니다' 싶으면 미련 없이 끊는 타입이야. 쿨한 게 장점인데, 가끔은 한 번 더 잡아보는 것도 후회를 줄여.",
    catchpoint: "금양(庚) + 수(子) = 쇠+물 → 차갑고 흐르는 에너지, 미련 없는 결단",
    bestMatch: "을미-m",
    worstMatch: "병오-m",
    rarity: 4,
  },

  // ── 113. 병진 (丙辰) 남성 — 화(양) + 토 ──
  {
    id: "병진-m",
    ilju: "병진",
    hanja: "丙辰",
    gender: "male",
    name: "자존감 풀충전",
    emoji: "🐉",
    tagline: "근자감으로 세상을 정복함",
    stemElement: "화(火)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-pop-orange",
    strengths: ["존재감", "설득력", "낙관"],
    weaknesses: ["자기 확신 강함", "주관이 너무 강함"],
    quote: "내가 하면 달라. 진짜야.",
    description: "태양이 용의 땅을 비추는 사주야. 화생토라 에너지가 자연스럽게 뻗어나가거든. 방에 들어서면 존재감이 딱 느껴지는 타입이야. 자신감에 실력이 따라오면 진짜 무적인데, 과신하면 주변이 하나둘 빠져나갈 수 있어.",
    catchpoint: "화양(丙) + 토(辰) = 태양이 용의 땅을 비춤 → 카리스마+스케일, 자연스러운 존재감",
    bestMatch: "임자-f",
    worstMatch: "임술-m",
    rarity: 5,
  },

  // ── 114. 병진 (丙辰) 여성 — 화(양) + 토 ──
  {
    id: "병진-f",
    ilju: "병진",
    hanja: "丙辰",
    gender: "female",
    name: "에너지 전염러",
    emoji: "🌅",
    tagline: "이 사람이랑 얘기하면 나도 모르게 고해성사하고 있음",
    stemElement: "화(火)",
    branchElement: "토(土)",
    yinyang: "양(陽)",
    tagColor: "bg-pop-orange",
    strengths: ["동기부여", "밝은 에너지", "포용력"],
    weaknesses: ["오버", "쉬지 않음"],
    quote: "할 수 있어! 못 할 이유가 어딨어!",
    description: "밝은 태양이 넓은 대지를 비추는 사주야. 화생토로 에너지가 주변에 자연스럽게 퍼지거든. 이 사람 옆에 있으면 '나도 뭔가 할 수 있을 것 같다'는 기분이 들어. 근데 본인이 항상 밝아야 한다는 부담을 내려놓을 줄도 알아야 해.",
    catchpoint: "화양(丙) + 토(辰) = 태양이 대지를 비춤 → 주변까지 살리는 에너지 전파력",
    bestMatch: "임자-m",
    worstMatch: "임술-f",
    rarity: 4,
  },

  // ── 115. 정사 (丁巳) 남성 — 화(음) + 화 ──
  {
    id: "정사-m",
    ilju: "정사",
    hanja: "丁巳",
    gender: "male",
    name: "몰입하면 시간 증발",
    emoji: "🔬",
    tagline: "꽂혀서 하다 보면 새벽 4시임",
    stemElement: "화(火)",
    branchElement: "화(火)",
    yinyang: "음(陰)",
    tagColor: "bg-pop-orange",
    strengths: ["몰입력", "열정", "깊이"],
    weaknesses: ["번아웃", "밀당 조절 어려움"],
    quote: "엥 벌써 이 시간이야? 방금 시작했는데...",
    description: "촛불이 또 불꽃을 만나는 사주야. 화(火) 두 겹이라 한번 빠지면 시간 감각이 사라져. 좋아하는 일에 몰입하면 진짜 무서운 집중력을 보여주거든. 근데 몸이 보내는 신호를 무시하면 확 무너질 수 있어.",
    catchpoint: "화음(丁) + 화(巳) = 불이 두 겹 → 몰입하면 세상이 사라지는 집중력",
    bestMatch: "임자-f",
    worstMatch: "경자-m",
    rarity: 4,
  },

  // ── 116. 정사 (丁巳) 여성 — 화(음) + 화 ──
  {
    id: "정사-f",
    ilju: "정사",
    hanja: "丁巳",
    gender: "female",
    name: "호불호 1초 결정",
    emoji: "🔥",
    tagline: "표정 못 숨김",
    stemElement: "화(火)",
    branchElement: "화(火)",
    yinyang: "음(陰)",
    tagColor: "bg-pop-orange",
    strengths: ["직관", "결단력", "솔직함"],
    weaknesses: ["감정 온도차 큼", "좋거나 싫거나 확실함"],
    quote: "호감? 3초면 알아.",
    description: "작은 불꽃이 또 불꽃 속에 있는 사주야. 화 두 겹이라 감정이 증폭되니까 좋고 싫음이 바로 나와. 중간이 없어서 주변이 당황할 때도 있는데, 이 솔직함 때문에 오히려 믿을 수 있는 사람이야. 근데 첫인상으로만 판단하면 놓치는 것도 있어.",
    catchpoint: "화음(丁) + 화(巳) = 불꽃 두 겹 → 감정 증폭, 호불호 즉각 반응",
    bestMatch: "임자-m",
    worstMatch: "경자-f",
    rarity: 4,
  },

  // ── 117. 경신 (庚申) 남성 — 금(양) + 금 ──
  {
    id: "경신-m",
    ilju: "경신",
    hanja: "庚申",
    gender: "male",
    name: "브레이크 고장",
    emoji: "🗡️",
    tagline: "돌아가는 길? 그냥 뚫음",
    stemElement: "금(金)",
    branchElement: "금(金)",
    yinyang: "양(陽)",
    tagColor: "bg-charcoal",
    strengths: ["추진력", "결단", "실행력"],
    weaknesses: ["도전이 과할 때", "원칙을 중시함"],
    quote: "돌아가? 그냥 뚫으면 되지.",
    description: "강철이 또 강철을 만나는 사주야. 금(金) 두 겹이라 한번 방향 잡으면 그냥 직진이야. 장애물이 있어도 피하지 않고 부딪히거든. 그 돌파력이 장점인데, 가끔은 돌아가는 게 더 빠른 길일 때도 있다는 거 기억해.",
    catchpoint: "금양(庚) + 금(申) = 강철+강철 → 방향 잡으면 직진만, 돌파력 극대화",
    bestMatch: "을묘-f",
    worstMatch: "병오-f",
    rarity: 5,
  },

  // ── 118. 경신 (庚申) 여성 — 금(양) + 금 ──
  {
    id: "경신-f",
    ilju: "경신",
    hanja: "庚申",
    gender: "female",
    name: "추구미 디테일",
    emoji: "💎",
    tagline: "남은 봐줘도 자기는 안 봐줌",
    stemElement: "금(金)",
    branchElement: "금(金)",
    yinyang: "양(陽)",
    tagColor: "bg-charcoal",
    strengths: ["자기관리", "높은 기준", "성과"],
    weaknesses: ["본인에게 너무 엄격", "기대치가 높은 편"],
    quote: "이 정도면 됐지 않아? ...아니, 다시 해.",
    description: "금(金) 두 겹이라 본인한테 진짜 독해. '이 정도면 됐지'가 없어서 계속 갈고 닦거든. 결과물은 항상 좋은데, 그 과정에서 본인이 너무 지칠 수 있어. 80점짜리 본인도 충분히 괜찮다는 거 기억해.",
    catchpoint: "금양(庚) + 금(申) = 쇠가 쇠를 만남 → 끊임없이 깎고 다듬는 자기 연마",
    bestMatch: "을묘-m",
    worstMatch: "병오-m",
    rarity: 5,
  },

  // ── 119. 계해 (癸亥) 남성 — 수(음) + 수 ──
  {
    id: "계해-m",
    ilju: "계해",
    hanja: "癸亥",
    gender: "male",
    name: "생각의 심해",
    emoji: "🌌",
    tagline: "생각하다 우주까지 갔다 옴",
    stemElement: "수(水)",
    branchElement: "수(水)",
    yinyang: "음(陰)",
    tagColor: "bg-pink",
    strengths: ["사색", "상상력", "깊은 이해"],
    weaknesses: ["이상이 높은 편", "행동이 느림"],
    quote: "근데 그거 생각해봤어? 시간이란 게 진짜 존재하는 건가?",
    description: "작은 물이 큰 바다를 만나는 사주야. 수(水) 두 겹이라 생각의 깊이가 장난 아니야. 다른 사람이 '뭐 먹지' 고민할 때 이 사람은 '인간이란 무엇인가' 생각하고 있거든. 근데 생각만 하면 아무것도 안 되니까 가끔은 일단 움직여봐.",
    catchpoint: "수음(癸) + 수(亥) = 물이 또 물 → 생각의 깊이가 끝없이 내려감",
    bestMatch: "병오-f",
    worstMatch: "무술-m",
    rarity: 5,
  },

  // ── 120. 계해 (癸亥) 여성 — 수(음) + 수 ──
  {
    id: "계해-f",
    ilju: "계해",
    hanja: "癸亥",
    gender: "female",
    name: "감정 스펀지",
    emoji: "🫧",
    tagline: "노래 듣다가 추억 여행 떠남",
    stemElement: "수(水)",
    branchElement: "수(水)",
    yinyang: "음(陰)",
    tagColor: "bg-pink",
    strengths: ["감수성", "예술적 감각", "공감"],
    weaknesses: ["감정 과부하", "현실보다 상상이 편함"],
    quote: "이 노래 가사 진짜... 나 얘기 같아.",
    description: "이슬비가 깊은 바다로 스며드는 사주야. 수(水) 두 겹이라 감성이 진짜 풍부해. 영화 보면 주인공보다 더 울고, 음악 들으면 온몸으로 느끼거든. 그 감성이 예술로 나오면 대단한데, 감정에 빠져서 현실을 놓치지 않도록 주의해.",
    catchpoint: "수음(癸) + 수(亥) = 물이 또 물 → 감성 채널이 두 배, 모든 걸 느낌",
    bestMatch: "병오-m",
    worstMatch: "무술-f",
    rarity: 5,
  },
];

/** ID로 일주 유형 찾기 */
export function getIljuType(id: string): IljuType | undefined {
  return ILJU_TYPES.find((t) => t.id === id);
}

/** 일주 + 성별로 찾기 */
export function findIljuType(ilju: string, gender: 'male' | 'female'): IljuType | undefined {
  return ILJU_TYPES.find((t) => t.ilju === ilju && t.gender === gender);
}
