import type { JSX } from "react";
import type { ElemKr } from "@/lib/day-fortune";

import { DoodleRitualPollackMiniSky } from "@/components/doodle-pollack-mini-sky";
import { DoodleRitualPollackFishSky, DoodleRitualPollackFishPink, DoodleRitualPollackFishYellow } from "@/components/doodle-pollack-fish-sky";

import {
  DoodleStar, DoodleMoon, DoodleCloud, DoodleHeart, DoodleSparkle,
  DoodleFire, DoodleSun, DoodleRainbow, DoodleWave, DoodleLightning,
  DoodleLeaf, DoodleFeather, DoodleSnowflake, DoodleMapleLeaf, DoodleSmiley,
  DoodleQuestionMark, DoodleSpeechBubble, DoodleBalloon,
  DoodlePizza, DoodleCoffee, DoodleBubbleTea, DoodleTeapot, DoodleMatcha,
  DoodleCroissant, DoodleDonut, DoodleStrawberry, DoodleLemon, DoodleRamen, DoodleJuiceBox,
  DoodleIceCream, DoodleCake, DoodleCandy, DoodleMacaron, DoodleCookie, DoodleWaffle, DoodleToast,
  DoodleFlower, DoodleTulip, DoodleRose, DoodleSunflower, DoodleCherryBlossom,
  DoodlePottedPlant, DoodleClover, DoodleDandelion, DoodleMushroom, DoodleCactus,
  DoodleRaindrop, DoodleSprout,
  DoodleCat, DoodleFrog, DoodleBear, DoodleFox, DoodleRabbit, DoodlePenguin,
  DoodleHamster, DoodleButterfly, DoodleChick, DoodleLadybug,
  DoodleBow, DoodleSunglasses, DoodleBucketHat, DoodleSneaker, DoodleHandbag,
  DoodleHeadphones, DoodleLipstick, DoodlePerfume, DoodleRing, DoodleNailPolish, DoodleYarn,
  DoodleLetter, DoodlePlane, DoodleMusicNote, DoodleSuitcase, DoodleTicket,
  DoodleUmbrella, DoodleCamera, DoodlePolaroid, DoodleDiary, DoodlePencil,
  DoodleBook, DoodleVinylRecord, DoodleCassette,
  DoodleChair, DoodleSofa, DoodleMirror, DoodleLamp, DoodleCandle,
  DoodleClock, DoodleHourglass, DoodleTray, DoodleBasket, DoodlePillow,
  DoodleVase, DoodleColorPalette, DoodleScissors,
  DoodleCrystal, DoodleGhost, DoodleCrown, DoodleKey, DoodlePlanet, DoodleRocket,
  DoodleChristmasTree, DoodleSnowman, DoodleJingleBell, DoodleReindeer, DoodleStocking,
  DoodleWatermelon, DoodleSeashell, DoodleStarfish, DoodlePalmTree, DoodleFlipFlops,
  DoodleAcorn, DoodlePumpkin, DoodleChestnut, DoodleGinkgoLeaf,
  DoodleCrystalBall, DoodleMagicWand, DoodleTarot, DoodleFortuneCookie,
  DoodleFortunePouch, DoodleLuckyPig, DoodleLuckyToad, DoodleGoldenCarp, DoodleYeopjeon, DoodlePeachLongevity,
  DoodleSaltJar, DoodleOnggiJar, DoodleWindChime, DoodleCompass,
  DoodleTalisman, DoodleGarlic, DoodleRedString, DoodleMagpie, DoodleTaegeuk,
  DoodlePeony, DoodleIncenseBurner, DoodleFuCharacter,
  DoodleRitualPollack,
  DoodleDragon, DoodleTiger, DoodleCrane, DoodleTurtle, DoodlePhoenix,
  DoodleShamanBell, DoodleShamanFan, DoodleDokkaebi,
  DoodleLotus, DoodlePrayerBeads, DoodleCross,
  DoodleGoldBar, DoodleRedLantern, DoodleHorseshoe, DoodleRedEnvelope,
  DoodlePartyPopper, DoodleTrophy, DoodleFireworks, DoodleGiftBox,
  DoodleUnicorn, DoodleWitchHat, DoodlePotion, DoodleShootingStar, DoodleUFO, DoodleAstronaut, DoodleAlien, DoodleCauldron, DoodleMagicTopHat, DoodleSaturn,
  DoodlePartyHat, DoodleConfetti, DoodleChampagne, DoodleBigRibbon, DoodleMedal, DoodleGarland, DoodleCakeSlice,
  DoodleDog, DoodleOwl, DoodleDuck, DoodleBee, DoodleWhale, DoodleDeer,
  DoodleCowFace, DoodleCow, DoodleHorseFace, DoodleHorse,
  DoodleSheepFace, DoodleSheep, DoodleMonkeyFace, DoodleMonkey,
  DoodleRoosterFace, DoodleRooster, DoodlePigFace, DoodlePig,
  DoodleLionFace, DoodleLion, DoodleElephantFace, DoodleElephant,
  DoodleDinoFace, DoodleDino, DoodlePandaFace, DoodlePanda,
  DoodleOctopusFace, DoodleOctopus, DoodleCrocFace, DoodleCroc,
  DoodleFlamingoFace, DoodleFlamingo,
  DoodleMap, DoodlePassport, DoodleBackpack, DoodleBicycle, DoodleGlobe,
  DoodleMitten, DoodleHotCocoa, DoodleBeachBall, DoodleSunHat, DoodleApple, DoodlePineCone,
  DoodleSushi, DoodleChocolate, DoodleOnigiri, DoodleTaiyaki,
  DoodleDiamond, DoodleComet, DoodleInfinity, DoodleSparkles,
  DoodleLavender, DoodleBamboo, DoodleWaterLily, DoodleHibiscus,
  DoodlePictureFrame, DoodleBookshelf, DoodleBlanket, DoodlePlantPot,
  DoodleDress, DoodleHighHeels, DoodleGlasses, DoodleEarring,
  DoodleJellyfish, DoodleSeahorse, DoodlePufferfish, DoodleTropicalFish,
  DoodleCrab, DoodleShrimp, DoodleCoral, DoodleClam, DoodleConch,
  DoodleBeachUmbrella, DoodleFloatTube, DoodleSurfboard,
  DoodleBucketSpade, DoodleSandcastle, DoodleBeachTowel, DoodleSunscreen, DoodleAnchor,
  DoodleSeagull, DoodleLighthouse, DoodleTropicalDrink,
  DoodleCharm, DoodlePull, DoodlePush, DoodleBackfire, DoodleConfidence, DoodleLocation,
  DoodleCalendar,
} from "@/components/doodles";

import {
  DoodleRitualPollackV1,
  DoodleRitualPollackSlimRed, DoodleRitualPollackSlimOrange, DoodleRitualPollackSlimYellow,
  DoodleRitualPollackSlimGreen, DoodleRitualPollackSlimSky, DoodleRitualPollackSlimViolet, DoodleRitualPollackSlimPink,
  DoodleRitualPollackShortV1,
  DoodleRitualPollackShortRed, DoodleRitualPollackShortOrange, DoodleRitualPollackShortYellow,
  DoodleRitualPollackShortGreen, DoodleRitualPollackShortSky, DoodleRitualPollackShortViolet, DoodleRitualPollackShortPink,
  DoodleRitualPollackV2,
  DoodleRitualPollackChubbyRed, DoodleRitualPollackChubbyOrange, DoodleRitualPollackChubbyYellow,
  DoodleRitualPollackChubbyGreen, DoodleRitualPollackChubbySky, DoodleRitualPollackChubbyViolet, DoodleRitualPollackChubbyPink,
  DoodleRitualPollackTwist,
} from "@/components/doodle-ritual-pollack";

export type DoodleComp = (props: { className?: string }) => JSX.Element;

/**
 * 스티커 오행 분류.
 * - "목"|"화"|"토"|"금"|"수": 해당 오행으로 확정
 * - "무": 무속성 확정 (오행색이 약한 음식·동물·패션 등) — 필터·방점수에서 제외
 * - "전체": 오행 종합/포괄형 (태극·부적류 등) — 방 5행 그래프에서 목·화·토·금·수 각 +1,
 *           필터에서는 모든 오행에 노출. "무"의 정반대.
 * - undefined: 아직 분류 안 됨 (마이그레이션 진행 중. 전부 채우면 필수로 승격)
 */
export type StickerElement = ElemKr | "무" | "전체";

export type DoodleEntry = {
  name: string;               // 영문 키 — 식별자, 불변, 고객 비노출
  label?: string;             // 한글 상품명 — 고객 노출 (감성 네이밍). 마이그레이션 중 옵셔널, 완료 후 필수 승격
  comp: DoodleComp;
  element: StickerElement;    // 오행 — 필터·방 오행점수 집계용. 필수 (303종 분류 완료, 2026-06-28 승격)
};
export type DoodleCategory = { id: string; label: string; stickers: DoodleEntry[] };

export const DOODLE_CATEGORIES: DoodleCategory[] = [
  {
    id: "basic",
    label: "감성 기본",
    stickers: [
      { name: "Star", label: "소원별", comp: DoodleStar, element: "화" },
      { name: "Moon", label: "보름달", comp: DoodleMoon, element: "수" },
      { name: "Cloud", label: "뭉게구름", comp: DoodleCloud, element: "수" },
      { name: "Heart", label: "하트", comp: DoodleHeart, element: "화" },
      { name: "Sparkle", label: "반짝이", comp: DoodleSparkle, element: "화" },
      { name: "Fire", label: "모닥불", comp: DoodleFire, element: "화" },
      { name: "Sun", label: "햇살", comp: DoodleSun, element: "화" },
      { name: "Rainbow", label: "무지개", comp: DoodleRainbow, element: "수" },
      { name: "Wave", label: "물결", comp: DoodleWave, element: "수" },
      { name: "Lightning", label: "번개", comp: DoodleLightning, element: "화" },
      { name: "Leaf", label: "잎새", comp: DoodleLeaf, element: "목" },
      { name: "Feather", label: "깃털", comp: DoodleFeather, element: "목" },
      { name: "Snowflake", label: "눈송이", comp: DoodleSnowflake, element: "수" },
      { name: "MapleLeaf", label: "단풍잎", comp: DoodleMapleLeaf, element: "목" },
      { name: "Smiley", label: "방긋", comp: DoodleSmiley, element: "화" },
      { name: "QuestionMark", label: "물음표", comp: DoodleQuestionMark, element: "무" },
      { name: "SpeechBubble", label: "말풍선", comp: DoodleSpeechBubble, element: "무" },
      { name: "Balloon", label: "풍선", comp: DoodleBalloon, element: "무" },
      { name: "Diamond", label: "다이아", comp: DoodleDiamond, element: "금" },
      { name: "Comet", label: "혜성", comp: DoodleComet, element: "화" },
      { name: "Infinity", label: "무한대", comp: DoodleInfinity, element: "무" },
      { name: "Sparkles", label: "반짝반짝", comp: DoodleSparkles, element: "화" },
    ],
  },
  {
    id: "food",
    label: "음식 & 카페",
    stickers: [
      { name: "Pizza", label: "피자", comp: DoodlePizza, element: "화" },
      { name: "Coffee", label: "커피", comp: DoodleCoffee, element: "수" },
      { name: "BubbleTea", label: "버블티", comp: DoodleBubbleTea, element: "수" },
      { name: "Teapot", label: "찻주전자", comp: DoodleTeapot, element: "수" },
      { name: "Matcha", label: "말차", comp: DoodleMatcha, element: "수" },
      { name: "Croissant", label: "크루아상", comp: DoodleCroissant, element: "화" },
      { name: "Donut", label: "도넛", comp: DoodleDonut, element: "토" },
      { name: "Strawberry", label: "딸기", comp: DoodleStrawberry, element: "목" },
      { name: "Lemon", label: "레몬", comp: DoodleLemon, element: "목" },
      { name: "Ramen", label: "라면", comp: DoodleRamen, element: "화" },
      { name: "JuiceBox", label: "주스팩", comp: DoodleJuiceBox, element: "수" },
      { name: "IceCream", label: "아이스크림", comp: DoodleIceCream, element: "수" },
      { name: "Cake", label: "케이크", comp: DoodleCake, element: "화" },
      { name: "Candy", label: "사탕", comp: DoodleCandy, element: "무" },
      { name: "Macaron", label: "마카롱", comp: DoodleMacaron, element: "화" },
      { name: "Cookie", label: "쿠키", comp: DoodleCookie, element: "토" },
      { name: "Waffle", label: "와플", comp: DoodleWaffle, element: "화" },
      { name: "Toast", label: "토스트", comp: DoodleToast, element: "화" },
      { name: "Sushi", label: "초밥", comp: DoodleSushi, element: "수" },
      { name: "Chocolate", label: "초콜릿", comp: DoodleChocolate, element: "목" },
      { name: "Onigiri", label: "주먹밥", comp: DoodleOnigiri, element: "목" },
      { name: "Taiyaki", label: "붕어빵", comp: DoodleTaiyaki, element: "토" },
    ],
  },
  {
    id: "nature",
    label: "꽃 & 자연",
    stickers: [
      { name: "Flower", label: "꽃", comp: DoodleFlower, element: "목" },
      { name: "Tulip", label: "튤립", comp: DoodleTulip, element: "목" },
      { name: "Rose", label: "장미", comp: DoodleRose, element: "목" },
      { name: "Sunflower", label: "해바라기", comp: DoodleSunflower, element: "목" },
      { name: "CherryBlossom", label: "벚꽃", comp: DoodleCherryBlossom, element: "목" },
      { name: "PottedPlant", label: "화분", comp: DoodlePottedPlant, element: "목" },
      { name: "Clover", label: "클로버", comp: DoodleClover, element: "목" },
      { name: "Dandelion", label: "민들레", comp: DoodleDandelion, element: "목" },
      { name: "Mushroom", label: "버섯", comp: DoodleMushroom, element: "토" },
      { name: "Cactus", label: "선인장", comp: DoodleCactus, element: "목" },
      { name: "Raindrop", label: "빗방울", comp: DoodleRaindrop, element: "수" },
      { name: "Sprout", label: "새싹", comp: DoodleSprout, element: "목" },
      { name: "Lavender", label: "라벤더", comp: DoodleLavender, element: "목" },
      { name: "Bamboo", label: "대나무", comp: DoodleBamboo, element: "목" },
      { name: "WaterLily", label: "수련", comp: DoodleWaterLily, element: "목" },
      { name: "Hibiscus", label: "히비스커스", comp: DoodleHibiscus, element: "목" },
    ],
  },
  {
    id: "animal",
    label: "동물",
    stickers: [
      { name: "Cat", label: "고양이", comp: DoodleCat, element: "금" },
      { name: "Frog", label: "개구리", comp: DoodleFrog, element: "수" },
      { name: "Bear", label: "곰", comp: DoodleBear, element: "토" },
      { name: "Fox", label: "여우", comp: DoodleFox, element: "화" },
      { name: "Rabbit", label: "토끼", comp: DoodleRabbit, element: "목" },
      { name: "Penguin", label: "펭귄", comp: DoodlePenguin, element: "수" },
      { name: "Hamster", label: "햄스터", comp: DoodleHamster, element: "수" },
      { name: "Butterfly", label: "나비", comp: DoodleButterfly, element: "목" },
      { name: "Chick", label: "병아리", comp: DoodleChick, element: "금" },
      { name: "Ladybug", label: "무당벌레", comp: DoodleLadybug, element: "목" },
      { name: "Dog", label: "강아지", comp: DoodleDog, element: "토" },
      { name: "Owl", label: "부엉이", comp: DoodleOwl, element: "금" },
      { name: "Duck", label: "오리", comp: DoodleDuck, element: "수" },
      { name: "Bee", label: "꿀벌", comp: DoodleBee, element: "목" },
      { name: "Whale", label: "고래", comp: DoodleWhale, element: "수" },
      { name: "Deer", label: "사슴", comp: DoodleDeer, element: "토" },
      { name: "Cow Face", label: "소 얼굴", comp: DoodleCowFace, element: "토" },
      { name: "Cow", label: "소", comp: DoodleCow, element: "토" },
      { name: "Horse Face", label: "말 얼굴", comp: DoodleHorseFace, element: "화" },
      { name: "Horse", label: "말", comp: DoodleHorse, element: "화" },
      { name: "Sheep Face", label: "양 얼굴", comp: DoodleSheepFace, element: "토" },
      { name: "Sheep", label: "양", comp: DoodleSheep, element: "토" },
      { name: "Monkey Face", label: "원숭이 얼굴", comp: DoodleMonkeyFace, element: "금" },
      { name: "Monkey", label: "원숭이", comp: DoodleMonkey, element: "금" },
      { name: "Rooster Face", label: "닭 얼굴", comp: DoodleRoosterFace, element: "금" },
      { name: "Rooster", label: "닭", comp: DoodleRooster, element: "금" },
      { name: "Pig Face", label: "돼지 얼굴", comp: DoodlePigFace, element: "수" },
      { name: "Pig", label: "돼지", comp: DoodlePig, element: "수" },
      { name: "Lion Face", label: "사자 얼굴", comp: DoodleLionFace, element: "토" },
      { name: "Lion", label: "사자", comp: DoodleLion, element: "토" },
      { name: "Elephant Face", label: "코끼리 얼굴", comp: DoodleElephantFace, element: "토" },
      { name: "Elephant", label: "코끼리", comp: DoodleElephant, element: "토" },
      { name: "Dino Face", label: "공룡 얼굴", comp: DoodleDinoFace, element: "토" },
      { name: "Dino", label: "공룡", comp: DoodleDino, element: "토" },
      { name: "Panda Face", label: "판다 얼굴", comp: DoodlePandaFace, element: "토" },
      { name: "Panda", label: "판다", comp: DoodlePanda, element: "토" },
      { name: "Octopus Face", label: "문어 얼굴", comp: DoodleOctopusFace, element: "수" },
      { name: "Octopus", label: "문어", comp: DoodleOctopus, element: "수" },
      { name: "Croc Face", label: "악어 얼굴", comp: DoodleCrocFace, element: "수" },
      { name: "Croc", label: "악어", comp: DoodleCroc, element: "수" },
      { name: "Flamingo Face", label: "플라밍고 얼굴", comp: DoodleFlamingoFace, element: "수" },
      { name: "Flamingo", label: "플라밍고", comp: DoodleFlamingo, element: "수" },
    ],
  },
  {
    id: "fashion",
    label: "패션 & 뷰티",
    stickers: [
      { name: "Bow", label: "리본", comp: DoodleBow, element: "화" },
      { name: "Sunglasses", label: "선글라스", comp: DoodleSunglasses, element: "금" },
      { name: "BucketHat", label: "버킷햇", comp: DoodleBucketHat, element: "목" },
      { name: "Sneaker", label: "운동화", comp: DoodleSneaker, element: "무" },
      { name: "Handbag", label: "핸드백", comp: DoodleHandbag, element: "화" },
      { name: "Headphones", label: "헤드폰", comp: DoodleHeadphones, element: "금" },
      { name: "Lipstick", label: "립스틱", comp: DoodleLipstick, element: "화" },
      { name: "Perfume", label: "향수", comp: DoodlePerfume, element: "수" },
      { name: "Ring", label: "반지", comp: DoodleRing, element: "금" },
      { name: "NailPolish", label: "매니큐어", comp: DoodleNailPolish, element: "수" },
      { name: "Yarn", label: "털실", comp: DoodleYarn, element: "목" },
      { name: "Dress", label: "드레스", comp: DoodleDress, element: "화" },
      { name: "HighHeels", label: "하이힐", comp: DoodleHighHeels, element: "금" },
      { name: "Glasses", label: "안경", comp: DoodleGlasses, element: "금" },
      { name: "Earring", label: "귀걸이", comp: DoodleEarring, element: "금" },
    ],
  },
  {
    id: "travel",
    label: "여행 & 일상",
    stickers: [
      { name: "Letter", label: "편지", comp: DoodleLetter, element: "목" },
      { name: "Plane", label: "비행기", comp: DoodlePlane, element: "금" },
      { name: "MusicNote", label: "음표", comp: DoodleMusicNote, element: "화" },
      { name: "Suitcase", label: "여행가방", comp: DoodleSuitcase, element: "수" },
      { name: "Ticket", label: "티켓", comp: DoodleTicket, element: "목" },
      { name: "Umbrella", label: "우산", comp: DoodleUmbrella, element: "수" },
      { name: "Camera", label: "카메라", comp: DoodleCamera, element: "금" },
      { name: "Polaroid", label: "폴라로이드", comp: DoodlePolaroid, element: "금" },
      { name: "Diary", label: "일기장", comp: DoodleDiary, element: "목" },
      { name: "Pencil", label: "연필", comp: DoodlePencil, element: "목" },
      { name: "Book", label: "책", comp: DoodleBook, element: "목" },
      { name: "VinylRecord", label: "레코드", comp: DoodleVinylRecord, element: "금" },
      { name: "Cassette", label: "카세트테이프", comp: DoodleCassette, element: "금" },
      { name: "Map", label: "지도", comp: DoodleMap, element: "목" },
      { name: "Passport", label: "여권", comp: DoodlePassport, element: "목" },
      { name: "Backpack", label: "백팩", comp: DoodleBackpack, element: "화" },
      { name: "Bicycle", label: "자전거", comp: DoodleBicycle, element: "금" },
      { name: "Globe", label: "지구본", comp: DoodleGlobe, element: "토" },
    ],
  },
  {
    id: "home",
    label: "홈 & 인테리어",
    stickers: [
      { name: "Chair", label: "의자", comp: DoodleChair, element: "목" },
      { name: "Sofa", label: "소파", comp: DoodleSofa, element: "목" },
      { name: "Mirror", label: "거울", comp: DoodleMirror, element: "금" },
      { name: "Lamp", label: "램프", comp: DoodleLamp, element: "화" },
      { name: "Candle", label: "캔들", comp: DoodleCandle, element: "화" },
      { name: "Clock", label: "시계", comp: DoodleClock, element: "금" },
      { name: "Hourglass", label: "모래시계", comp: DoodleHourglass, element: "토" },
      { name: "Tray", label: "쟁반", comp: DoodleTray, element: "금" },
      { name: "Basket", label: "바구니", comp: DoodleBasket, element: "목" },
      { name: "Pillow", label: "쿠션", comp: DoodlePillow, element: "목" },
      { name: "Vase", label: "꽃병", comp: DoodleVase, element: "토" },
      { name: "ColorPalette", label: "팔레트", comp: DoodleColorPalette, element: "무" },
      { name: "Scissors", label: "가위", comp: DoodleScissors, element: "금" },
      { name: "PictureFrame", label: "액자", comp: DoodlePictureFrame, element: "목" },
      { name: "Bookshelf", label: "책장", comp: DoodleBookshelf, element: "목" },
      { name: "Blanket", label: "담요", comp: DoodleBlanket, element: "목" },
      { name: "PlantPot", label: "화분", comp: DoodlePlantPot, element: "목" },
    ],
  },
  {
    id: "fantasy",
    label: "판타지 & 우주",
    stickers: [
      { name: "Crystal", label: "크리스탈", comp: DoodleCrystal, element: "금" },
      { name: "Ghost", label: "유령", comp: DoodleGhost, element: "수" },
      { name: "Crown", label: "왕관", comp: DoodleCrown, element: "금" },
      { name: "Key", label: "열쇠", comp: DoodleKey, element: "금" },
      { name: "Planet", label: "행성", comp: DoodlePlanet, element: "토" },
      { name: "Rocket", label: "로켓", comp: DoodleRocket, element: "금" },
      { name: "Unicorn", label: "유니콘", comp: DoodleUnicorn, element: "무" },
      { name: "WitchHat", label: "마녀모자", comp: DoodleWitchHat, element: "목" },
      { name: "Potion", label: "물약", comp: DoodlePotion, element: "수" },
      { name: "ShootingStar", label: "별똥별", comp: DoodleShootingStar, element: "화" },
      { name: "UFO", label: "유에프오", comp: DoodleUFO, element: "금" },
      { name: "Astronaut", label: "우주인", comp: DoodleAstronaut, element: "무" },
      { name: "Alien", label: "외계인", comp: DoodleAlien, element: "무" },
      { name: "Cauldron", label: "가마솥", comp: DoodleCauldron, element: "금" },
      { name: "MagicTopHat", label: "마술모자", comp: DoodleMagicTopHat, element: "목" },
      { name: "Saturn", label: "토성", comp: DoodleSaturn, element: "토" },
    ],
  },
  {
    id: "season",
    label: "계절",
    stickers: [
      { name: "ChristmasTree", label: "크리스마스트리", comp: DoodleChristmasTree, element: "목" },
      { name: "Snowman", label: "눈사람", comp: DoodleSnowman, element: "수" },
      { name: "JingleBell", label: "종", comp: DoodleJingleBell, element: "금" },
      { name: "Reindeer", label: "순록", comp: DoodleReindeer, element: "토" },
      { name: "Stocking", label: "크리스마스양말", comp: DoodleStocking, element: "화" },
      { name: "Watermelon", label: "수박", comp: DoodleWatermelon, element: "목" },
      { name: "Seashell", label: "조개껍데기", comp: DoodleSeashell, element: "수" },
      { name: "Starfish", label: "불가사리", comp: DoodleStarfish, element: "수" },
      { name: "PalmTree", label: "야자수", comp: DoodlePalmTree, element: "목" },
      { name: "FlipFlops", label: "쪼리", comp: DoodleFlipFlops, element: "토" },
      { name: "Acorn", label: "도토리", comp: DoodleAcorn, element: "목" },
      { name: "Pumpkin", label: "호박", comp: DoodlePumpkin, element: "목" },
      { name: "Chestnut", label: "밤", comp: DoodleChestnut, element: "목" },
      { name: "GinkgoLeaf", label: "은행잎", comp: DoodleGinkgoLeaf, element: "목" },
      { name: "Mitten", label: "벙어리장갑", comp: DoodleMitten, element: "화" },
      { name: "HotCocoa", label: "핫초코", comp: DoodleHotCocoa, element: "수" },
      { name: "BeachBall", label: "비치볼", comp: DoodleBeachBall, element: "수" },
      { name: "SunHat", label: "썬햇", comp: DoodleSunHat, element: "목" },
      { name: "Apple", label: "사과", comp: DoodleApple, element: "목" },
      { name: "PineCone", label: "솔방울", comp: DoodlePineCone, element: "목" },
    ],
  },
  {
    id: "mystic",
    label: "사주 · 미신 · 종교",
    stickers: [
      { name: "CrystalBall", label: "수정구", comp: DoodleCrystalBall, element: "전체" },
      { name: "MagicWand", label: "마법봉", comp: DoodleMagicWand, element: "전체" },
      { name: "Tarot", label: "타로카드", comp: DoodleTarot, element: "전체" },
      { name: "FortuneCookie", label: "포춘쿠키", comp: DoodleFortuneCookie, element: "토" },
      { name: "FortunePouch", label: "복주머니", comp: DoodleFortunePouch, element: "전체" },
      { name: "LuckyPig", label: "복돼지", comp: DoodleLuckyPig, element: "금" },
      { name: "LuckyToad", label: "금두꺼비", comp: DoodleLuckyToad, element: "금" },
      { name: "GoldenCarp", label: "금잉어", comp: DoodleGoldenCarp, element: "수" },
      { name: "Yeopjeon", label: "엽전", comp: DoodleYeopjeon, element: "금" },
      { name: "PeachLongevity", label: "천도복숭아", comp: DoodlePeachLongevity, element: "목" },
      { name: "SaltJar", label: "소금단지", comp: DoodleSaltJar, element: "전체" },
      { name: "OnggiJar", label: "옹기", comp: DoodleOnggiJar, element: "토" },
      { name: "WindChime", label: "풍경", comp: DoodleWindChime, element: "금" },
      { name: "Compass", label: "나침반", comp: DoodleCompass, element: "금" },
      { name: "Talisman", label: "부적", comp: DoodleTalisman, element: "화" },
      { name: "Garlic", label: "마늘", comp: DoodleGarlic, element: "목" },
      { name: "RedString", label: "붉은실", comp: DoodleRedString, element: "화" },
      { name: "Magpie", label: "까치", comp: DoodleMagpie, element: "전체" },
      { name: "Taegeuk", label: "태극", comp: DoodleTaegeuk, element: "전체" },
      { name: "Peony", label: "모란", comp: DoodlePeony, element: "목" },
      { name: "IncenseBurner", label: "향로", comp: DoodleIncenseBurner, element: "화" },
      { name: "FuCharacter", label: "복(福)자", comp: DoodleFuCharacter, element: "전체" },
      { name: "Dragon", label: "청룡", comp: DoodleDragon, element: "전체" },
      { name: "Tiger", label: "백호", comp: DoodleTiger, element: "금" },
      { name: "Crane", label: "학", comp: DoodleCrane, element: "전체" },
      { name: "Turtle", label: "현무", comp: DoodleTurtle, element: "수" },
      { name: "Phoenix", label: "주작", comp: DoodlePhoenix, element: "전체" },
      { name: "ShamanBell", label: "무당방울", comp: DoodleShamanBell, element: "금" },
      { name: "ShamanFan", label: "무당부채", comp: DoodleShamanFan, element: "전체" },
      { name: "Dokkaebi", label: "도깨비", comp: DoodleDokkaebi, element: "전체" },
      { name: "Lotus", label: "연꽃", comp: DoodleLotus, element: "목" },
      { name: "PrayerBeads", label: "염주", comp: DoodlePrayerBeads, element: "목" },
      { name: "Cross", label: "십자가", comp: DoodleCross, element: "전체" },
      { name: "GoldBar", label: "금괴", comp: DoodleGoldBar, element: "금" },
      { name: "RedLantern", label: "홍등", comp: DoodleRedLantern, element: "화" },
      { name: "Horseshoe", label: "편자", comp: DoodleHorseshoe, element: "금" },
      { name: "RedEnvelope", label: "복돈봉투", comp: DoodleRedEnvelope, element: "금" },
      { name: "RitualPollack", label: "북어", comp: DoodleRitualPollack, element: "목" },
      { name: "Pollack Slim 🪵", label: "북어 (가는·기본)", comp: DoodleRitualPollackV1, element: "목" },
      { name: "Pollack Slim 🔴", label: "북어 (가는·빨강)", comp: DoodleRitualPollackSlimRed, element: "화" },
      { name: "Pollack Slim 🟠", label: "북어 (가는·주황)", comp: DoodleRitualPollackSlimOrange, element: "화" },
      { name: "Pollack Slim 🟡", label: "북어 (가는·노랑)", comp: DoodleRitualPollackSlimYellow, element: "토" },
      { name: "Pollack Slim 🟢", label: "북어 (가는·초록)", comp: DoodleRitualPollackSlimGreen, element: "목" },
      { name: "Pollack Slim 🔵", label: "북어 (가는·파랑)", comp: DoodleRitualPollackSlimSky, element: "수" },
      { name: "Pollack Slim 🟣", label: "북어 (가는·보라)", comp: DoodleRitualPollackSlimViolet, element: "수" },
      { name: "Pollack Slim 🩷", label: "북어 (가는·분홍)", comp: DoodleRitualPollackSlimPink, element: "화" },
      { name: "Pollack Short 🪵", label: "북어 (짧은·기본)", comp: DoodleRitualPollackShortV1, element: "목" },
      { name: "Pollack Short 🔴", label: "북어 (짧은·빨강)", comp: DoodleRitualPollackShortRed, element: "화" },
      { name: "Pollack Short 🟠", label: "북어 (짧은·주황)", comp: DoodleRitualPollackShortOrange, element: "화" },
      { name: "Pollack Short 🟡", label: "북어 (짧은·노랑)", comp: DoodleRitualPollackShortYellow, element: "토" },
      { name: "Pollack Short 🟢", label: "북어 (짧은·초록)", comp: DoodleRitualPollackShortGreen, element: "목" },
      { name: "Pollack Short 🔵", label: "북어 (짧은·파랑)", comp: DoodleRitualPollackShortSky, element: "수" },
      { name: "Pollack Mini 🔵", label: "북어 (미니·파랑)", comp: DoodleRitualPollackMiniSky, element: "수" },
      { name: "Pollack Fish 🔵", label: "북어 (물고기형·파랑)", comp: DoodleRitualPollackFishSky, element: "수" },
      { name: "Pollack Fish 🩷", label: "북어 (물고기형·분홍)", comp: DoodleRitualPollackFishPink, element: "화" },
      { name: "Pollack Fish 🟡", label: "북어 (물고기형·노랑)", comp: DoodleRitualPollackFishYellow, element: "토" },
      { name: "Pollack Short 🟣", label: "북어 (짧은·보라)", comp: DoodleRitualPollackShortViolet, element: "수" },
      { name: "Pollack Short 🩷", label: "북어 (짧은·분홍)", comp: DoodleRitualPollackShortPink, element: "화" },
      { name: "Pollack Chubby 🪵", label: "북어 (통통·기본)", comp: DoodleRitualPollackV2, element: "목" },
      { name: "Pollack Chubby 🔴", label: "북어 (통통·빨강)", comp: DoodleRitualPollackChubbyRed, element: "화" },
      { name: "Pollack Chubby 🟠", label: "북어 (통통·주황)", comp: DoodleRitualPollackChubbyOrange, element: "화" },
      { name: "Pollack Chubby 🟡", label: "북어 (통통·노랑)", comp: DoodleRitualPollackChubbyYellow, element: "토" },
      { name: "Pollack Chubby 🟢", label: "북어 (통통·초록)", comp: DoodleRitualPollackChubbyGreen, element: "목" },
      { name: "Pollack Chubby 🔵", label: "북어 (통통·파랑)", comp: DoodleRitualPollackChubbySky, element: "수" },
      { name: "Pollack Chubby 🟣", label: "북어 (통통·보라)", comp: DoodleRitualPollackChubbyViolet, element: "수" },
      { name: "Pollack Chubby 🩷", label: "북어 (통통·분홍)", comp: DoodleRitualPollackChubbyPink, element: "화" },
      { name: "Pollack Twist 🪢", label: "북어 (꽈배기 끈)", comp: DoodleRitualPollackTwist, element: "목" },
    ],
  },
  {
    id: "party",
    label: "파티 & 축하",
    stickers: [
      { name: "PartyPopper", label: "폭죽", comp: DoodlePartyPopper, element: "화" },
      { name: "Trophy", label: "트로피", comp: DoodleTrophy, element: "금" },
      { name: "Fireworks", label: "불꽃놀이", comp: DoodleFireworks, element: "화" },
      { name: "GiftBox", label: "선물상자", comp: DoodleGiftBox, element: "목" },
      { name: "PartyHat", label: "파티모자", comp: DoodlePartyHat, element: "목" },
      { name: "Confetti", label: "꽃가루", comp: DoodleConfetti, element: "목" },
      { name: "Champagne", label: "샴페인", comp: DoodleChampagne, element: "수" },
      { name: "BigRibbon", label: "큰리본", comp: DoodleBigRibbon, element: "화" },
      { name: "Medal", label: "메달", comp: DoodleMedal, element: "금" },
      { name: "Garland", label: "갈런드", comp: DoodleGarland, element: "목" },
      { name: "CakeSlice", label: "케이크조각", comp: DoodleCakeSlice, element: "화" },
    ],
  },
  {
    id: "summer",
    label: "여름 바캉스",
    stickers: [
      { name: "BeachBall", label: "비치볼", comp: DoodleBeachBall, element: "수" },
      { name: "BeachUmbrella", label: "비치파라솔", comp: DoodleBeachUmbrella, element: "수" },
      { name: "FloatTube", label: "튜브", comp: DoodleFloatTube, element: "수" },
      { name: "Surfboard", label: "서핑보드", comp: DoodleSurfboard, element: "수" },
      { name: "FlipFlops", label: "쪼리", comp: DoodleFlipFlops, element: "토" },
      { name: "SunHat", label: "썬햇", comp: DoodleSunHat, element: "목" },
      { name: "Sunscreen", label: "선크림", comp: DoodleSunscreen, element: "화" },
      { name: "BeachTowel", label: "비치타월", comp: DoodleBeachTowel, element: "수" },
      { name: "BucketSpade", label: "모래놀이세트", comp: DoodleBucketSpade, element: "토" },
      { name: "Sandcastle", label: "모래성", comp: DoodleSandcastle, element: "토" },
      { name: "PalmTree", label: "야자수", comp: DoodlePalmTree, element: "목" },
      { name: "Wave", label: "물결", comp: DoodleWave, element: "수" },
      { name: "Seashell", label: "조개껍데기", comp: DoodleSeashell, element: "수" },
      { name: "Starfish", label: "불가사리", comp: DoodleStarfish, element: "수" },
      { name: "Clam", label: "조개", comp: DoodleClam, element: "수" },
      { name: "Conch", label: "소라", comp: DoodleConch, element: "수" },
      { name: "Coral", label: "산호", comp: DoodleCoral, element: "수" },
      { name: "Jellyfish", label: "해파리", comp: DoodleJellyfish, element: "수" },
      { name: "Seahorse", label: "해마", comp: DoodleSeahorse, element: "수" },
      { name: "Pufferfish", label: "복어", comp: DoodlePufferfish, element: "수" },
      { name: "TropicalFish", label: "열대어", comp: DoodleTropicalFish, element: "수" },
      { name: "Crab", label: "게", comp: DoodleCrab, element: "수" },
      { name: "Shrimp", label: "새우", comp: DoodleShrimp, element: "수" },
      { name: "Octopus", label: "문어", comp: DoodleOctopus, element: "수" },
      { name: "Anchor", label: "닻", comp: DoodleAnchor, element: "금" },
      { name: "Lighthouse", label: "등대", comp: DoodleLighthouse, element: "화" },
      { name: "Seagull", label: "갈매기", comp: DoodleSeagull, element: "수" },
      { name: "TropicalDrink", label: "트로피컬드링크", comp: DoodleTropicalDrink, element: "수" },
      { name: "Watermelon", label: "수박", comp: DoodleWatermelon, element: "목" },
      { name: "IceCream", label: "아이스크림", comp: DoodleIceCream, element: "수" },
    ],
  },
  {
    id: "concept",
    label: "관계 & 심리",
    stickers: [
      { name: "Charm", label: "매력", comp: DoodleCharm, element: "화" },
      { name: "Pull", label: "당기다", comp: DoodlePull, element: "금" },
      { name: "Push", label: "밀다", comp: DoodlePush, element: "무" },
      { name: "Backfire", label: "역효과", comp: DoodleBackfire, element: "화" },
      { name: "Confidence", label: "확신", comp: DoodleConfidence, element: "금" },
      { name: "Location", label: "장소", comp: DoodleLocation, element: "토" },
      { name: "Calendar", label: "달력", comp: DoodleCalendar, element: "목" },
      { name: "ColorPalette", label: "팔레트", comp: DoodleColorPalette, element: "무" },
    ],
  },
];

export const ALL_STICKERS: DoodleEntry[] = DOODLE_CATEGORIES.flatMap(c => c.stickers);
